const fs = require('fs');
const path = require('path');

const contextPath = path.join(__dirname, 'client/src/contexts/LanguageContext.js');
const homePath = path.join(__dirname, 'client/src/pages/HomePage.js');

const newTranslations = `
    , mr: {
        welcome: "नमस्कार!",
        tagline: "तुमचा योग्य जोडीदार शोधा",
        heroTitle: "तुमचा परिपूर्ण विवाह बायोडाटा तयार करा",
        heroSubtitle: "व्यावसायिक टेम्पलेट्स • रिअल-टाइम प्रिव्ह्यू • इन्स्टंट PDF",
        startFree: "मोफत सुरू करा →",
        learnMore: "अधिक जाणून घ्या ↓",
        features: "वैशिष्ट्ये",
        pricing: "किंमत",
        signIn: "लॉग इन करा",
        getStarted: "सुरू करा",
        dashboard: "डॅशबोर्ड",
        whyChoose: "ShadiBio का निवडावे?",
        stunningBiodatas: "एक सुंदर बायोडाटा तयार करण्यासाठी आवश्यक असलेले सर्व काही",
        beautifulTemplates: "सुंदर टेम्पलेट्स",
        traditionalModern: "पारंपारिक आणि आधुनिक डिझाईन्स",
        realTimePreview: "रिअल-टाइम प्रिव्ह्यू",
        liveUpdates: "तुम्ही टाईप करताच लाईव्ह अपडेट्स",
        pdfDownload: "PDF डाउनलोड",
        highQualityPdfs: "उच्च दर्जाचे इन्स्टंट PDF",
        privacyControls: "गोपनीयता नियंत्रणे",
        yourDataControl: "तुमचा डेटा, तुमचे नियंत्रण",
        multiLanguage: "बहु-भाषिक समर्थन",
        languagesSupported: "अनेक भाषांमध्ये उपलब्ध",
        smartFeatures: "स्मार्ट वैशिष्ट्ये",
        autoCalcHistory: "ऑटो-कॅल्क्युलेशन आणि व्हर्जन हिस्ट्री",
        happyUsers: "संतुष्ट वापरकर्ते",
        biodatasCreated: "बायोडाटा तयार केले",
        uptime: "अपटाईम",
        userRating: "वापरकर्ता रेटिंग",
        pricingTitle: "सोपी आणि पारदर्शक किंमत",
        pricingSubtitle: "तुम्हाला योग्य वाटणारा प्लॅन निवडा",
        mostPopular: "सर्वाधिक लोकप्रिय",
        free: "मोफत",
        premium: "प्रीमियम",
        lifetime: "लाईफटाईम",
        forever: "कायमस्वरूपी",
        month: "/महिना",
        oneTime: "एकदाच",
        goPremium: "प्रीमियम घ्या",
        getLifetime: "लाईफटाईम घ्या",
        footerText: "© 2024 ShadiBio. तुमच्या परिपूर्ण जोडीदाराला शोधण्यासाठी ❤️ ने बनवलेले",
        privacy: "गोपनीयता",
        terms: "अटी",
        contact: "संपर्क",
        signInAccount: "तुमच्या खात्यात लॉग इन करा",
        emailAddress: "ईमेल पत्ता",
        password: "पासवर्ड",
        rememberMe: "मला लक्षात ठेवा",
        signingIn: "लॉग इन करत आहे...",
        notHaveAccount: "खाते नाही? साइन अप करा",
        createAccount: "नवीन खाते तयार करा",
        fullName: "पूर्ण नाव",
        confirmPassword: "पासवर्डची पुष्टी करा",
        creatingAccount: "खाते तयार करत आहे...",
        alreadyHaveAccount: "आधीपासूनच खाते आहे? लॉग इन करा",
        or: "किंवा"
    },
    gu: {
        welcome: "નમસ્તે!",
        tagline: "તમારો યોગ્ય જીવનસાથી શોધો",
        heroTitle: "તમારો સંપૂર્ણ લગ્ન બાયોડેટા બનાવો",
        heroSubtitle: "વ્યાવસાયિક ટેમ્પ્લેટ્સ • રીઅલ-ટાઇમ પ્રિવ્યૂ • ઇન્સ્ટન્ટ PDF",
        startFree: "મફત શરૂ કરો →",
        learnMore: "વધુ જાણો ↓",
        features: "વિશેષતા",
        pricing: "કિંમત",
        signIn: "લોગ ઇન કરો",
        getStarted: "શરૂ કરો",
        dashboard: "ડેશબોર્ડ",
        whyChoose: "ShadiBio શા માટે પસંદ કરો?",
        stunningBiodatas: "સુંદર બાયોડેટા બનાવવા માટે જરૂરી બધું જ",
        beautifulTemplates: "સુંદર ટેમ્પ્લેટ્સ",
        traditionalModern: "પરંપરાગત અને આધુનિક ડિઝાઇન",
        realTimePreview: "રીઅલ-ટાઇમ પ્રિવ્યૂ",
        liveUpdates: "જ્યારે તમે ટાઇપ કરો ત્યારે લાઇવ અપડેટ્સ",
        pdfDownload: "PDF ડાઉનલોડ",
        highQualityPdfs: "ઉચ્ચ ગુણવત્તાવાળા ઇન્સ્ટન્ટ PDF",
        privacyControls: "ગોપનીયતા નિયંત્રણો",
        yourDataControl: "તમારો ડેટા, તમારું નિયંત્રણ",
        multiLanguage: "બહુભાષી આધાર",
        languagesSupported: "અનેક ભાષાઓમાં સમર્થિત",
        smartFeatures: "સ્માર્ટ સુવિધાઓ",
        autoCalcHistory: "ઓટો-કેલ્ક્યુલેશન અને વર્ઝન હિસ્ટ્રી",
        happyUsers: "સંતુષ્ટ વપરાશકર્તાઓ",
        biodatasCreated: "બાયોડેટા બનાવ્યા",
        uptime: "અપટાઇમ",
        userRating: "વપરાશકર્તા રેટિંગ",
        pricingTitle: "સરળ અને પારદર્શક કિંમત",
        pricingSubtitle: "તમને અનુકૂળ પ્લાન પસંદ કરો",
        mostPopular: "સૌથી લોકપ્રિય",
        free: "મફત",
        premium: "પ્રીમિયમ",
        lifetime: "લાઇફટાઇમ",
        forever: "કાયમ માટે",
        month: "/મહિનો",
        oneTime: "એકવાર",
        goPremium: "પ્રીમિયમ મેળવો",
        getLifetime: "લાઇફટાઇમ મેળવો",
        footerText: "© 2024 ShadiBio. તમારા સંપૂર્ણ જીવનસાથીને શોધવા માટે ❤️ થી બનાવેલ",
        privacy: "ગોપનીયતા",
        terms: "શરતો",
        contact: "સંપર્ક",
        signInAccount: "તમારા એકાઉન્ટમાં લૉગ ઇન કરો",
        emailAddress: "ઇમેઇલ સરનામું",
        password: "પાસવર્ડ",
        rememberMe: "મને યાદ રાખો",
        signingIn: "લોગ ઇન થઈ રહ્યું છે...",
        notHaveAccount: "એકાઉન્ટ નથી? સાઇન અપ કરો",
        createAccount: "નવું એકાઉન્ટ બનાવો",
        fullName: "પૂરું નામ",
        confirmPassword: "પાસવર્ડની પુષ્ટિ કરો",
        creatingAccount: "એકાઉન્ટ બની રહ્યું છે...",
        alreadyHaveAccount: "પહેલાથી જ એકાઉન્ટ છે? લોગ ઇન કરો",
        or: "અથવા"
    },
    bn: {
        welcome: "নমস্কার!",
        tagline: "আপনার পারফেক্ট জীবনসঙ্গী খুঁজুন",
        heroTitle: "আপনার নিখুঁত বিয়ের বায়োডাটা তৈরি করুন",
        heroSubtitle: "প্রফেশনাল টেমপ্লেট • রিয়েল-টাইম প্রিভিউ • ইনস্ট্যান্ট PDF",
        startFree: "বিনামূল্যে শুরু করুন →",
        learnMore: "আরও জানুন ↓",
        features: "বৈশিষ্ট্য",
        pricing: "মূল্য নির্ধারণ",
        signIn: "লগ ইন করুন",
        getStarted: "শুরু করুন",
        dashboard: "ড্যাশবোর্ড",
        whyChoose: "কেন ShadiBio বেছে নেবেন?",
        stunningBiodatas: "একটি সুন্দর বায়োডাটা তৈরি করার জন্য আপনার যা যা প্রয়োজন",
        beautifulTemplates: "সুন্দর টেমপ্লেট",
        traditionalModern: "ঐতিহ্যবাহী এবং আধুনিক ডিজাইন",
        realTimePreview: "রিয়েল-টাইম প্রিভিউ",
        liveUpdates: "আপনি টাইপ করার সাথে সাথে লাইভ আপডেট",
        pdfDownload: "PDF ডাউনলোড",
        highQualityPdfs: "উচ্চ-মানের ইনস্ট্যান্ট PDF",
        privacyControls: "গোপনীয়তা নিয়ন্ত্রণ",
        yourDataControl: "আপনার ডেটা, আপনার নিয়ন্ত্রণ",
        multiLanguage: "বহু-ভাষা সমর্থন",
        languagesSupported: "একাধিক ভাষা সমর্থিত",
        smartFeatures: "স্মার্ট বৈশিষ্ট্য",
        autoCalcHistory: "অটো-ক্যালকুলেশন এবং সংস্করণ ইতিহাস",
        happyUsers: "সন্তুষ্ট ব্যবহারকারী",
        biodatasCreated: "বায়োডাটা তৈরি করা হয়েছে",
        uptime: "আপটাইম",
        userRating: "ইউজার রেটিং",
        pricingTitle: "সহজ এবং স্বচ্ছ মূল্য",
        pricingSubtitle: "আপনার জন্য উপযুক্ত প্ল্যান বেছে নিন",
        mostPopular: "সবচেয়ে জনপ্রিয়",
        free: "বিনামূল্যে",
        premium: "প্রিমিয়াম",
        lifetime: "লাইফটাইম",
        forever: "চিরকালের জন্য",
        month: "/মাস",
        oneTime: "এককালীন",
        goPremium: "প্রিমিয়াম নিন",
        getLifetime: "লাইফটাইম নিন",
        footerText: "© 2024 ShadiBio. আপনার নিখুঁত সঙ্গী খুঁজে পাওয়ার জন্য ❤️ দিয়ে তৈরি",
        privacy: "গোপনীয়তা",
        terms: "শর্তাবলী",
        contact: "যোগাযোগ",
        signInAccount: "আপনার অ্যাকাউন্টে লগ ইন করুন",
        emailAddress: "ইমেইল ঠিকানা",
        password: "পাসওয়ার্ড",
        rememberMe: "আমাকে মনে রাখুন",
        signingIn: "লগ ইন করা হচ্ছে...",
        notHaveAccount: "অ্যাকাউন্ট নেই? সাইন আপ করুন",
        createAccount: "নতুন অ্যাকাউন্ট তৈরি করুন",
        fullName: "পুরো নাম",
        confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
        creatingAccount: "অ্যাকাউন্ট তৈরি হচ্ছে...",
        alreadyHaveAccount: "ইতোমধ্যে অ্যাকাউন্ট আছে? লগ ইন করুন",
        or: "অথবা"
    },
    pa: {
        welcome: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ!",
        tagline: "ਆਪਣਾ ਜੀਵਨ ਸਾਥੀ ਲੱਭੋ",
        heroTitle: "ਆਪਣਾ ਵਧੀਆ ਵਿਆਹ ਬਾਇਓਡਾਟਾ ਬਣਾਓ",
        heroSubtitle: "ਪੇਸ਼ੇਵਰ ਟੈਂਪਲੇਟਸ • ਰੀਅਲ-ਟਾਈਮ ਪ੍ਰੀਵਿਊ • ਤੁਰੰਤ PDF",
        startFree: "ਮੁਫਤ ਸ਼ੁਰੂ ਕਰੋ →",
        learnMore: "ਹੋਰ ਜਾਣੋ ↓",
        features: "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
        pricing: "ਕੀਮਤ",
        signIn: "ਲਾਗੂ ਕਰੋ",
        getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
        dashboard: "ਡੈਸ਼ਬੋਰਡ",
        whyChoose: "ShadiBio ਕਿਉਂ ਚੁਣੀਏ?",
        stunningBiodatas: "ਸੁੰਦਰ ਬਾਇਓਡਾਟਾ ਬਣਾਉਣ ਲਈ ਸਭ ਕੁਝ",
        beautifulTemplates: "ਸੁੰਦਰ ਟੈਂਪਲੇਟਸ",
        traditionalModern: "ਰਵਾਇਤੀ ਅਤੇ ਆਧੁਨਿਕ ਡਿਜ਼ਾਇਨ",
        realTimePreview: "ਰੀਅਲ-ਟਾਈਮ ਪ੍ਰੀਵਿਊ",
        liveUpdates: "ਜਦੋਂ ਤੁਸੀਂ ਲਿਖਦੇ ਹੋ ਲਾਈਵ ਅਪਡੇਟਸ",
        pdfDownload: "PDF ਡਾਊਨਲੋਡ",
        highQualityPdfs: "ਉੱਚ ਗੁਣਵੱਤਾ ਵਾਲੇ ਤੁਰੰਤ PDF",
        privacyControls: "ਸੁਰੱਖਿਆ ਨਿਯੰਤਰਣ",
        yourDataControl: "ਤੁਹਾਡਾ ਡੇਟਾ, ਤੁਹਾਡਾ ਨਿਯੰਤਰਣ",
        multiLanguage: "ਬਹੁ-ਭਾਸ਼ਾਈ ਸਹਿਯੋਗ",
        languagesSupported: "ਕਈ ਭਾਸ਼ਾਵਾਂ ਸਮਰਥਿਤ ਹਨ",
        smartFeatures: "ਸਮਾਰਟ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
        autoCalcHistory: "ਆਟੋ-ਗਣਨਾ ਅਤੇ ਇਤਿਹਾਸ",
        happyUsers: "ਖੁਸ਼ ਉਪਭੋਗਤਾ",
        biodatasCreated: "ਬਣੇ ਬਾਇਓਡਾਟੇ",
        uptime: "ਅਪਟਾਈਮ",
        userRating: "ਉਪਭੋਗਤਾ ਰੇਟਿੰਗ",
        pricingTitle: "ਆਸਾਨ ਅਤੇ ਸਾਫ਼ ਕੀਮਤਾਂ",
        pricingSubtitle: "ਉਹ ਪਲਾਨ ਚੁਣੋ ਜੋ ਤੁਹਾਡੇ ਲਈ ਸਹੀ ਹੈ",
        mostPopular: "ਸਭ ਤੋਂ ਮਸ਼ਹੂਰ",
        free: "ਮੁਫਤ",
        premium: "ਪ੍ਰੀਮੀਅਮ",
        lifetime: "ਸਾਰੀ ਉਮਰ",
        forever: "ਹਮੇਸ਼ਾ ਲਈ",
        month: "/ਮਹੀਨਾ",
        oneTime: "ਇੱਕ ਵਾਰ",
        goPremium: "ਪ੍ਰੀਮੀਅਮ ਲਵੋ",
        getLifetime: "ਲਾਈਫਟਾਈਮ ਲਵੋ",
        footerText: "© 2024 ShadiBio. ਆਪਣੇ ਸਾਥੀ ਨੂੰ ਲੱਭਣ ਲਈ ❤️ ਨਾਲ ਬਣਾਇਆ",
        privacy: "ਪ੍ਰਾਈਵੇਸੀ",
        terms: "ਨਿਯਮ",
        contact: "ਸੰਪਰਕ",
        signInAccount: "ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਲਾਗਇਨ ਕਰੋ",
        emailAddress: "ਈਮੇਲ ਪਤਾ",
        password: "ਪਾਸਵਰਡ",
        rememberMe: "ਮੈਨੂੰ ਯਾਦ ਰੱਖੋ",
        signingIn: "ਲਾਗਇਨ ਹੋ ਰਿਹਾ ਹੈ...",
        notHaveAccount: "ਖਾਤਾ ਨਹੀਂ ਹੈ? ਸਾਈਨ ਅੱਪ ਕਰੋ",
        createAccount: "ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ",
        fullName: "ਪੂਰਾ ਨਾਂ",
        confirmPassword: "ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
        creatingAccount: "ਖਾਤਾ ਬਣਾ ਰਿਹਾ ਹੈ...",
        alreadyHaveAccount: "ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ? ਲਾਗਇਨ ਕਰੋ",
        or: "ਜਾਂ"
    },
    or: {
        welcome: "ନମସ୍କାର!",
        tagline: "ଆପଣଙ୍କର ଉପଯୁକ୍ତ ଜୀବନସାଥୀ ଖୋଜନ୍ତୁ",
        heroTitle: "ଆପଣଙ୍କର ଉପଯୁକ୍ତ ବିବାହ ବାୟୋଡାଟା ତିଆରି କରନ୍ତୁ",
        heroSubtitle: "ପ୍ରୋଫେସନାଲ୍ ଟେମ୍ପଲେଟ୍ • ରିଅଲ୍-ଟାଇମ୍ ପ୍ରିଭ୍ୟୁ • ତୁରନ୍ତ PDF",
        startFree: "ମାଗଣାରେ ଆରମ୍ଭ କରନ୍ତୁ →",
        learnMore: "ଅଧିକ ଜାଣନ୍ତୁ ↓",
        features: "ବୈଶିଷ୍ଟ୍ୟଗୁଡିକ",
        pricing: "ମୂଲ୍ୟ",
        signIn: "ଲଗ୍ ଇନ୍ କରନ୍ତୁ",
        getStarted: "ଆରମ୍ଭ କରନ୍ତୁ",
        dashboard: "ଡ୍ୟାସବୋର୍ଡ",
        whyChoose: "ShadiBio କାହିଁକି ବାଛିବେ?",
        stunningBiodatas: "ଏକ ସୁନ୍ଦର ବାୟୋଡାଟା ତିଆରି ପାଇଁ ସବୁକିଛି",
        beautifulTemplates: "ସୁନ୍ଦର ଟେମ୍ପଲେଟ୍",
        traditionalModern: "ପାରମ୍ପାରିକ ଏବଂ ଆଧୁନିକ ଡିଜାଇନ୍",
        realTimePreview: "ରିଅଲ୍-ଟାଇମ୍ ପ୍ରିଭ୍ୟୁ",
        liveUpdates: "ଟାଇପ୍ କରୁଥିବା ବେଳେ ଲାଇଭ୍ ଅପଡେଟ୍",
        pdfDownload: "PDF ଡାଉନଲୋଡ୍",
        highQualityPdfs: "ଉଚ୍ଚ-ଗୁଣାତ୍ମକ ତୁରନ୍ତ PDF",
        privacyControls: "ଗୋପନୀୟତା ନିୟନ୍ତ୍ରଣ",
        yourDataControl: "ଆପଣଙ୍କର ଡାଟା, ଆପଣଙ୍କର ନିୟନ୍ତ୍ରଣ",
        multiLanguage: "ବହୁ-ଭାଷା ସମର୍ଥନ",
        languagesSupported: "ଏକାଧିକ ଭାଷା ସମର୍ଥିତ",
        smartFeatures: "ସ୍ମାର୍ଟ ଫିଚର",
        autoCalcHistory: "ଅଟୋ-କାଲକୁଲେସନ୍ ଏବଂ ଭର୍ଜନ୍ ହିଷ୍ଟ୍ରି",
        happyUsers: "ସନ୍ତୁଷ୍ଟ ଉପଯୋଗକର୍ତ୍ତା",
        biodatasCreated: "ବାୟୋଡାଟା ତିଆରି ହୋଇଛି",
        uptime: "ଅପଟାଇମ୍",
        userRating: "ୟୁଜର୍ ରେଟିଂ",
        pricingTitle: "ସହଜ ଏବଂ ସ୍ୱଚ୍ଛ ମୂଲ୍ୟ",
        pricingSubtitle: "ଆପଣଙ୍କ ପାଇଁ ଉପଯୁକ୍ତ ପ୍ଲାନ୍ ବାଛନ୍ତୁ",
        mostPopular: "ସବୁଠାରୁ ଲୋକପ୍ରିୟ",
        free: "ମାଗଣା",
        premium: "ପ୍ରିମିୟମ୍",
        lifetime: "ଲାଇଫ୍ ଟାଇମ୍",
        forever: "ସବୁଦିନ ପାଇଁ",
        month: "/ମାସ",
        oneTime: "ଥରେ",
        goPremium: "ପ୍ରିମିୟମ୍ ନିଅନ୍ତୁ",
        getLifetime: "ଲାଇଫ୍ ଟାଇମ୍ ନିଅନ୍ତୁ",
        footerText: "© 2024 ShadiBio. ଆପଣଙ୍କର ଜୀବନସାଥୀ ଖୋଜିବା ପାଇଁ ❤️ ରେ ତିଆରି",
        privacy: "ଗୋପନୀୟତା",
        terms: "ସର୍ତ୍ତାବଳୀ",
        contact: "ଯୋଗାଯୋଗ",
        signInAccount: "ଆପଣଙ୍କର ଆକାଉଣ୍ଟକୁ ଲଗ୍ ଇନ୍ କରନ୍ତୁ",
        emailAddress: "ଇମେଲ୍ ଠିକଣା",
        password: "ପାସୱାର୍ଡ",
        rememberMe: "ମୋତେ ମନେ ରଖନ୍ତୁ",
        signingIn: "ଲଗ୍ ଇନ୍ ହେଉଛି...",
        notHaveAccount: "ଆକାଉଣ୍ଟ ନାହିଁ? ସାଇନ୍ ଅପ୍ କରନ୍ତୁ",
        createAccount: "ନୂଆ ଆକାଉଣ୍ଟ ଖୋଲନ୍ତୁ",
        fullName: "ପୁରା ନାମ",
        confirmPassword: "ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ",
        creatingAccount: "ଆକାଉଣ୍ଟ ତିଆରି ହେଉଛି...",
        alreadyHaveAccount: "ଆକାଉଣ୍ଟ ଅଛି? ଲଗ୍ ଇନ୍ କରନ୍ତୁ",
        or: "କିମ୍ବା"
    },
    ur: {
        welcome: "خوش آمدید!",
        tagline: "اپنا بہترین جیون ساتھی تلاش کریں",
        heroTitle: "اپنا بہترین شادی کا بائیوڈیٹا بنائیں",
        heroSubtitle: "پیشہ ورانہ ٹیمپلیٹس • ریئل ٹائم پیش نظارہ • فوری PDF",
        startFree: "مفت میں شروع کریں ←",
        learnMore: "مزید جانیں ↓",
        features: "خصوصیات",
        pricing: "قیمت",
        signIn: "لاگ ان کریں",
        getStarted: "شروع کریں",
        dashboard: "ڈیش بورڈ",
        whyChoose: "ShadiBio کیوں چنیں؟",
        stunningBiodatas: "خوبصورت بائیوڈیٹا بنانے کے لیے درکار ہر چیز",
        beautifulTemplates: "خوبصورت ٹیمپلیٹس",
        traditionalModern: "روایتی اور جدید ڈیزائن",
        realTimePreview: "ریئل ٹائم پیش نظارہ",
        liveUpdates: "ٹائپ کرتے وقت لائیو اپڈیٹس",
        pdfDownload: "PDF ڈاؤن لوڈ",
        highQualityPdfs: "اعلی معیار کی فوری PDF",
        privacyControls: "رازداری کے کنٹرولز",
        yourDataControl: "آپ کا ڈیٹا، آپ کا کنٹرول",
        multiLanguage: "کثیر لسانی سپورٹ",
        languagesSupported: "متعدد زبانوں کی حمایت",
        smartFeatures: "سمارٹ خصوصیات",
        autoCalcHistory: "آٹو کیلکولیشن اور ورژن ہسٹری",
        happyUsers: "خوش صارفین",
        biodatasCreated: "بائیوڈیٹا بنائے گئے",
        uptime: "اپ ٹائم",
        userRating: "صارفین کی درجہ بندی",
        pricingTitle: "آسان اور شفاف قیمتیں",
        pricingSubtitle: "وہ پلان چنیں جو آپ کے لیے صحیح ہو",
        mostPopular: "سب سے زیادہ مقبول",
        free: "مفت",
        premium: "پریمیم",
        lifetime: "لائف ٹائم",
        forever: "ہمیشہ کے لیے",
        month: "/مہینہ",
        oneTime: "ایک بار",
        goPremium: "پریمیم حاصل کریں",
        getLifetime: "لائف ٹائم حاصل کریں",
        footerText: "© 2024 ShadiBio. آپ کے ساتھی کو تلاش کرنے کے لیے ❤️ سے بنایا گیا",
        privacy: "رازداری",
        terms: "شرائط",
        contact: "رابطہ",
        signInAccount: "اپنے اکاؤنٹ میں لاگ ان کریں",
        emailAddress: "ای میل ایڈریس",
        password: "پاس ورڈ",
        rememberMe: "مجھے یاد رکھیں",
        signingIn: "لاگ ان ہو رہا ہے...",
        notHaveAccount: "اکاؤنٹ نہیں ہے؟ سائن اپ کریں",
        createAccount: "نیا اکاؤنٹ بنائیں",
        fullName: "پورا نام",
        confirmPassword: "پاس ورڈ کی تصدیق کریں",
        creatingAccount: "اکاؤنٹ بن رہا ہے...",
        alreadyHaveAccount: "پہلے سے اکاؤنٹ ہے؟ لاگ ان کریں",
        or: "یا"
    },
    as: {
        welcome: "স্বাগতম!",
        tagline: "আপোনাৰ যোগ্য জীৱনসংগী বিচাৰক",
        heroTitle: "আপোনাৰ নিখুঁত বিবাহৰ বায়োডাটা প্ৰস্তুত কৰক",
        heroSubtitle: "প্ৰফেছনেল টেম্পলেট • ৰিয়েল-টাইম প্ৰিভিউ • লগে লগে PDF",
        startFree: "বিনামূল্যে আৰম্ভ কৰক →",
        learnMore: "অধিক জানক ↓",
        features: "বৈশিষ্ট্য",
        pricing: "মূল্যনিৰ্ধাৰণ",
        signIn: "লগ ইন কৰক",
        getStarted: "আৰম্ভ কৰক",
        dashboard: "ডেশ্বব'ৰ্ড",
        whyChoose: "ShadiBio কিয় বাছনি কৰিব?",
        stunningBiodatas: "এটি সুন্দৰ বায়োডাটা সৃষ্টি কৰিবৰ বাবে প্ৰয়োজনীয় সকলো বস্তু",
        beautifulTemplates: "সুন্দৰ টেম্পলেট",
        traditionalModern: "পৰম্পৰাগত আৰু আধুনিক ডিজাইন",
        realTimePreview: "ৰিয়েল-টাইম প্ৰিভিউ",
        liveUpdates: "আপুনি টাইপ কৰাৰ লগে লগে লাইভ আপডেট",
        pdfDownload: "PDF ডাউনলোড",
        highQualityPdfs: "উচ্চ-মানদণ্ডৰ তাৎক্ষণিক PDF",
        privacyControls: "গোপনীয়তা নিয়ন্ত্ৰণ",
        yourDataControl: "আপোনাৰ ডেটা, আপোনাৰ নিয়ন্ত্ৰণ",
        multiLanguage: "বহু-ভাষাৰ সমৰ্থন",
        languagesSupported: "একাধিক ভাষা সমৰ্থিত",
        smartFeatures: "স্মাৰ্ট বৈশিষ্ট্য",
        autoCalcHistory: "অটো-কেলকুলেচন আৰু সংস্কৰণ ইতিহাস",
        happyUsers: "সন্তুষ্ট ব্যৱহাৰকাৰী",
        biodatasCreated: "বায়োডাটা সৃষ্টি কৰা হৈছে",
        uptime: "আপটাইম",
        userRating: "ইউজাৰ ৰেটিং",
        pricingTitle: "সহজ আৰু স্বচ্ছ মূল্য",
        pricingSubtitle: "আপোনাৰ বাবে উপযুক্ত প্লেন বাছি লওঁক",
        mostPopular: "আটাইতকৈ জনপ্ৰিয়",
        free: "বিনামূলীয়া",
        premium: "প্ৰিমিয়াম",
        lifetime: "লাইফটাইম",
        forever: "চিৰজীৱনৰ বাবে",
        month: "/মাহ",
        oneTime: "এবাৰ",
        goPremium: "প্ৰিমিয়াম লওঁক",
        getLifetime: "লাইফটাইম লওঁক",
        footerText: "© 2024 ShadiBio. আপোনাৰ নিখুঁত সংগী বিচাৰি পাবলৈ ❤️ দি প্ৰস্তুত কৰা হৈছে",
        privacy: "গোপনীয়তা",
        terms: "চৰ্তসমূহ",
        contact: "যোগাযোগ",
        signInAccount: "আপোনাৰ একাউণ্টত লগ ইন কৰক",
        emailAddress: "ইমেইল ঠিকনা",
        password: "পাছৱৰ্ড",
        rememberMe: "মোক মনত ৰাখক",
        signingIn: "লগ ইন হৈ আছে...",
        notHaveAccount: "একাউণ্ট নাই? ছাইন আপ কৰক",
        createAccount: "নতুন একাউণ্ট খোলক",
        fullName: "সম্পূৰ্ণ নাম",
        confirmPassword: "পাছৱৰ্ড নিশ্চিত কৰক",
        creatingAccount: "একাউণ্ট প্ৰস্তুত হৈ আছে...",
        alreadyHaveAccount: "ইতিমধ্যে একাউণ্ট আছে? লগ ইন কৰক",
        or: "বা"
    },
    mai: {
        welcome: "प्रणाम!",
        tagline: "अपन नीक जीवनसाथी खोजू",
        heroTitle: "अपन उत्तम विवाहक बायोडाटा बनाउ",
        heroSubtitle: "प्रोफेशनल टेम्पलेट • रियल-टाइम प्रीव्यू • तुरंत PDF",
        startFree: "मुफ्त मे शुरू करू →",
        learnMore: "आरो जनू ↓",
        features: "विशेषतासभ",
        pricing: "कीमत",
        signIn: "लॉग इन करू",
        getStarted: "शुरू करू",
        dashboard: "डैशबोर्ड",
        whyChoose: "ShadiBio किएक चुनी?",
        stunningBiodatas: "सुंदर बायोडाटा बनाबय लेल सब किछु",
        beautifulTemplates: "सुंदर टेम्पलेट्स",
        traditionalModern: "पारंपरिक आ आधुनिक डिजाइन",
        realTimePreview: "रियल-टाइम प्रीव्यू",
        liveUpdates: "टाइप करैत काल लाइव अपडेट",
        pdfDownload: "PDF डाउनलोड",
        highQualityPdfs: "बढ़िया क्वालिटीक तुरंत PDF",
        privacyControls: "गोपनीयता नियंत्रण",
        yourDataControl: "अहांक डेटा, अहांक नियंत्रण",
        multiLanguage: "बहु-भाषी",
        languagesSupported: "ढेर रास भाषा समर्थित",
        smartFeatures: "स्मार्ट फीचर्स",
        autoCalcHistory: "ऑटो-कैलकुलेशन आ वर्जन हिस्ट्री",
        happyUsers: "खुश उपयोगकर्ता",
        biodatasCreated: "बायोडाटा बनल",
        uptime: "अपटाइम",
        userRating: "उपयोगकर्ता रेटिंग",
        pricingTitle: "आसान आ पारदर्शी कीमत",
        pricingSubtitle: "अपन लेल नीक प्लान चुनी",
        mostPopular: "सबसँ बेसी लोकप्रिय",
        free: "मुफ्त",
        premium: "प्रीमियम",
        lifetime: "लाइफटाइम",
        forever: "हमेशा लेल",
        month: "/महीना",
        oneTime: "एक बेर",
        goPremium: "प्रीमियम ली",
        getLifetime: "लाइफटाइम ली",
        footerText: "© 2024 ShadiBio. अहांक जीवनसाथी खोजय लेल ❤️ सँ बनल",
        privacy: "गोपनीयता",
        terms: "नियम",
        contact: "संपर्क",
        signInAccount: "अपन खाता मे लॉग इन करू",
        emailAddress: "ईमेल पता",
        password: "पासवर्ड",
        rememberMe: "हमरा याद राखू",
        signingIn: "लॉग इन भ रहल अछि...",
        notHaveAccount: "खाता नहि अछि? साइन अप करू",
        createAccount: "नवा खाता बनाउ",
        fullName: "पूरा नाम",
        confirmPassword: "पासवर्डक पुष्टि करू",
        creatingAccount: "खाता बन रहल अछि...",
        alreadyHaveAccount: "पहिले सँ खाता अछि? लॉग इन करू",
        or: "वा"
    },
    sd: {
        welcome: "ڀلي ڪري آيا!",
        tagline: "پنهنجو بهترين جيون ساٿي ڳوليو",
        heroTitle: "پنهنجو شادي جو بهترين بائيوڊيٽا ٺاهيو",
        heroSubtitle: "پروفيشنل ٽيمپليٽس • لائيو ڏيکاءُ • فوراً PDF",
        startFree: "مفت ۾ شروع ڪريو ←",
        learnMore: "وڌيڪ ڄاڻو ↓",
        features: "خاصيتون",
        pricing: "قيمتون",
        signIn: "لاگ ان ٿيو",
        getStarted: "شروع ڪريو",
        dashboard: "ڊيش بورڊ",
        whyChoose: "ShadiBio ڇو چونڊيو؟",
        stunningBiodatas: "هڪ سٺو بائيوڊيٽا ٺاهڻ لاءِ ضروري هر شئي",
        beautifulTemplates: "خوبصورت ٽيمپليٽس",
        traditionalModern: "روايتي ۽ جديد ڊزائينون",
        realTimePreview: "ريئل ٽائيم ڏيکاءُ",
        liveUpdates: "ٽائپ ڪندي ئي لائيو اپڊيٽس",
        pdfDownload: "PDF ڊائونلوڊ ڪريو",
        highQualityPdfs: "اعليٰ معيار جا فوري PDF",
        privacyControls: "پرائيويسي ڪنٽرول",
        yourDataControl: "توهان جي ڊيٽا، توهان جو ڪنٽرول",
        multiLanguage: "گهڻين ٻولين جي سپورٽ",
        languagesSupported: "ڪيتريون ئي ٻوليون سپورٽ ٿيل",
        smartFeatures: "سمارٽ فيچرز",
        autoCalcHistory: "آٽو ڪيلڪيوليشن ۽ ورزن هسٽري",
        happyUsers: "خوش گراهڪ",
        biodatasCreated: "بائيوڊيٽا ٺهيا",
        uptime: "اپ ٽائيم",
        userRating: "يوزر ريٽنگ",
        pricingTitle: "آسان ۽ شفاف قيمت",
        pricingSubtitle: "پنهنجي پسند جو پلان چونڊيو",
        mostPopular: "سڀ کان وڌيڪ مشهور",
        free: "مفت",
        premium: "پريميئم",
        lifetime: "لائف ٽائيم",
        forever: "هميشه لاءِ",
        month: "/مهينو",
        oneTime: "هڪ دفعو",
        goPremium: "پريميئم وٺو",
        getLifetime: "لائف ٽائيم وٺو",
        footerText: "© 2024 ShadiBio. توهان جو جيون ساٿي ڳولڻ لاءِ ❤️ سان ٺهيل",
        privacy: "پرائيويسي",
        terms: "شرطون",
        contact: "رابطو",
        signInAccount: "پنهنجي اڪائونٽ ۾ لاگ ان ٿيو",
        emailAddress: "اي ميل ائڊريس",
        password: "پاسورڊ",
        rememberMe: "مون کي ياد رکو",
        signingIn: "لاگ ان ٿي رهيو آهي...",
        notHaveAccount: "اڪائونٽ ناهي؟ سائن اپ ڪريو",
        createAccount: "نئون اڪائونٽ ٺاهيو",
        fullName: "پورو نالو",
        confirmPassword: "پاسورڊ جي پڪ ڪريو",
        creatingAccount: "اڪائونٽ ٺهي رهيو آهي...",
        alreadyHaveAccount: "پهريان ئي اڪائونٽ آهي؟ لاگ ان ٿيو",
        or: "يا"
    },
    kok: {
        welcome: "येवकार!",
        tagline: "तुमचो योग्य जोडीदार सोदात",
        heroTitle: "तुमचो सर्वोत्तम लग्न बायोडाटा तयार करात",
        heroSubtitle: "प्रोफेशनल टेम्पलेट्स • रिअल-टायम प्रिव्ह्यू • इन्स्टंट PDF",
        startFree: "फुकट सुरू करात →",
        learnMore: "अधिक जाणून घेयात ↓",
        features: "वैशिष्ट्यां",
        pricing: "मोल",
        signIn: "लॉग इन करात",
        getStarted: "सुरू करात",
        dashboard: "डॅशबोर्ड",
        whyChoose: "ShadiBio कित्याक निवडप?",
        stunningBiodatas: "एक सुंदर बायोडाटा तयार करपाक जाय आशिल्लें सगळें",
        beautifulTemplates: "सुंदर टेम्पलेट्स",
        traditionalModern: "पारंपारिक आणि आधुनिक डिझायनी",
        realTimePreview: "रिअल-टायम प्रिव्ह्यू",
        liveUpdates: "टायप करिनाफुडें लायव्ह अपडेट",
        pdfDownload: "PDF डाऊनलोड",
        highQualityPdfs: "उच्च दर्जाचे इन्स्टंट PDF",
        privacyControls: "गोपनीयता नियंत्रणां",
        yourDataControl: "तुमचो डेटा, तुमचें नियंत्रण",
        multiLanguage: "बहुभाषिक आदार",
        languagesSupported: "बरेच भासांक आदार",
        smartFeatures: "स्मार्ट फीचर्स",
        autoCalcHistory: "ऑटो-कॅल्क्युलेशन आणि व्हर्जन हिस्ट्री",
        happyUsers: "संतुष्ट वापरपी",
        biodatasCreated: "बायोडाटा तयार केले",
        uptime: "अपटायम",
        userRating: "वापरपी रेटिंग",
        pricingTitle: "सोपें आणि पारदर्शक मोल",
        pricingSubtitle: "तुमकां फाव तो प्लॅन निवडा",
        mostPopular: "सगळ्यांत लोकप्रिय",
        free: "फुकट",
        premium: "प्रीमियम",
        lifetime: "लायफटायम",
        forever: "कायमस्वरुपी",
        month: "/महिने",
        oneTime: "एकाच वेळार",
        goPremium: "प्रीमियम घेयात",
        getLifetime: "लायफटायम घेयात",
        footerText: "© 2024 ShadiBio. तुमचो परिपूर्ण जोडीदार सोदपाक ❤️-न तयार केलां",
        privacy: "गोपनीयता",
        terms: "अटी",
        contact: "संपर्क",
        signInAccount: "तुमच्या खात्यांत लॉग इन करात",
        emailAddress: "ईमेल पत्तो",
        password: "पासवर्ड",
        rememberMe: "म्हाका याद दवर",
        signingIn: "लॉग इन जाता...",
        notHaveAccount: "खातें ना? सायन अप करात",
        createAccount: "नवें खातें तयार करात",
        fullName: "पुराय नांव",
        confirmPassword: "पासवर्ड कन्फर्म करात",
        creatingAccount: "खातें तयार जाता...",
        alreadyHaveAccount: "आदींच खातें आसा? लॉग इन करात",
        or: "वां"
    },
    mni: {
        welcome: "ꯈꯨꯔꯨꯃꯖꯔꯤ!",
        tagline: "ꯅꯍꯥꯛꯀꯤ ꯄꯨꯟꯁꯤ ꯀꯣꯞꯄꯥ ꯊꯤꯕꯤꯌꯨ",
        heroTitle: "ꯅꯍꯥꯛꯀꯤ ꯄꯔꯐꯦꯛꯠ ꯂꯨꯍꯣꯡꯕꯒꯤ ꯕꯥꯌꯣꯗꯥꯇꯥ ꯁꯦꯝꯕꯤꯌꯨ",
        heroSubtitle: "ꯄ꯭ꯔꯣꯐꯦꯁꯅꯦꯜ ꯇꯦꯝꯄ꯭ꯂꯦꯠꯁ • ꯔꯤꯌꯦꯜ-ꯇꯥꯏꯝ ꯄ꯭ꯔꯤꯚꯤꯎ • ꯏꯟꯁꯇꯦꯟꯠ PDF",
        startFree: "ꯐ꯭ꯔꯤꯗꯥ ꯍꯧꯕꯤꯌꯨ →",
        learnMore: "ꯑꯍꯦꯟꯕꯥ ꯈꯪꯕꯤꯌꯨ ↓",
        features: "ꯐꯤꯆꯔꯁꯤꯡ",
        pricing: "ꯃꯃꯜ",
        signIn: "ꯂꯣꯒꯤꯟ",
        getStarted: "ꯍꯧꯕꯤꯌꯨ",
        dashboard: "ꯗꯦꯁꯕꯣꯔ꯭ꯗ",
        whyChoose: "ShadiBio ꯀꯔꯤꯒꯤ ꯈꯟꯕꯤꯒꯅꯤ?",
        stunningBiodatas: "ꯐꯖꯕꯥ ꯕꯥꯌꯣꯗꯥꯇꯥ ꯁꯦꯝꯅꯕꯥ ꯃꯊꯧ ꯇꯥꯕꯥ ꯄꯨꯝꯅꯃꯛ",
        beautifulTemplates: "ꯐꯖꯔꯕꯥ ꯇꯦꯝꯄ꯭ꯂꯦꯠꯁꯤꯡ",
        traditionalModern: "ꯇ꯭ꯔꯦꯗꯤꯁꯅꯦꯜ ꯑꯃꯁꯨꯡ ꯃꯣꯗꯔꯟ ꯗꯤꯖꯥꯏꯟꯁꯤꯡ",
        realTimePreview: "ꯔꯤꯌꯦꯜ-ꯇꯥꯏꯝ ꯄ꯭ꯔꯤꯚꯤꯎ",
        liveUpdates: "ꯅꯍꯥꯛꯅꯥ ꯇꯥꯏꯞ ꯇꯧꯕꯒꯥ ꯂꯣꯏꯅꯅꯥ ꯂꯥꯏꯚ ꯑꯄꯗꯦꯠ",
        pdfDownload: "PDF ꯗꯥꯎꯟꯂꯣꯗ",
        highQualityPdfs: "ꯍꯥꯏ-ꯀ꯭ꯋꯥꯂꯤꯇꯤ ꯏꯟꯁꯇꯦꯟꯠ PDF",
        privacyControls: "ꯄ꯭ꯔꯥꯏꯚꯦꯁꯤ ꯀꯟꯇ꯭ꯔꯣꯜꯁꯤꯡ",
        yourDataControl: "ꯅꯍꯥꯛꯀꯤ ꯗꯦꯇꯥ, ꯅꯍꯥꯛꯀꯤ ꯀꯟꯇ꯭ꯔꯣꯜ",
        multiLanguage: "ꯃꯜꯇꯤ-ꯂꯦꯡꯒꯨꯋꯦꯖ ꯁꯄꯣꯔꯠ",
        languagesSupported: "ꯂꯣꯟ ꯀꯌꯥ ꯁꯄꯣꯔꯠ ꯇꯧꯔꯤ",
        smartFeatures: "ꯁ꯭ꯃꯥꯔꯠ ꯐꯤꯆꯔꯁꯤꯡ",
        autoCalcHistory: "ꯑꯣꯇꯣ-ꯀꯦꯜꯀꯨꯂꯦꯁꯟ ꯑꯃꯁꯨꯡ ꯚꯔꯖꯟ ꯍꯤꯁꯇ꯭ꯔꯤ",
        happyUsers: "ꯅꯨꯡꯉꯥꯏꯔꯕꯥ ꯌꯨꯖꯔꯁꯤꯡ",
        biodatasCreated: "ꯕꯥꯌꯣꯗꯥꯇꯥ ꯁꯦꯝꯈ꯭ꯔꯦ",
        uptime: "ꯑꯞꯇꯥꯏꯝ",
        userRating: "ꯌꯨꯖꯔ ꯔꯦꯇꯤꯡ",
        pricingTitle: "ꯏꯂꯥꯏ ꯂꯥꯏꯕꯥ, ꯇ꯭ꯔꯥꯟꯁꯄꯔꯦꯟꯠ ꯃꯃꯜ",
        pricingSubtitle: "ꯅꯍꯥꯛꯇꯥ ꯆꯨꯟꯅꯕꯥ ꯄ꯭ꯂꯥꯟ ꯈꯟꯕꯤꯌꯨ",
        mostPopular: "ꯈ꯭ꯋꯥꯏꯗꯒꯤ ꯄꯣꯄꯨꯂꯔ",
        free: "ꯐ꯭ꯔꯤ",
        premium: "ꯄ꯭ꯔꯤꯃꯤꯌꯝ",
        lifetime: "ꯂꯥꯏꯐꯇꯥꯏꯝ",
        forever: "ꯃꯇꯝ ꯆꯨꯞꯄꯒꯤ",
        month: "/ꯊꯥꯒꯤ",
        oneTime: "ꯑꯃꯨꯛꯈꯛ",
        goPremium: "ꯄ꯭ꯔꯤꯃꯤꯌꯝ ꯂꯧꯕꯤꯌꯨ",
        getLifetime: "ꯂꯥꯏꯐꯇꯥꯏꯝ ꯂꯧꯕꯤꯌꯨ",
        footerText: "© 2024 ShadiBio. ꯅꯍꯥꯛꯀꯤ ꯄꯥꯔꯠꯅꯔ ꯊꯤꯕꯗꯥ ꯃꯇꯦꯡ ꯄꯥꯡꯅꯕꯥ ❤️ ꯒꯥ ꯂꯣꯏꯅꯅꯥ ꯁꯦꯝꯕꯥ",
        privacy: "ꯄ꯭ꯔꯥꯏꯚꯦꯁꯤ",
        terms: "ꯇꯔꯝꯁ",
        contact: "ꯀꯟꯇꯦꯛ",
        signInAccount: "ꯅꯍꯥꯛꯀꯤ ꯑꯦꯀꯥꯎꯟꯠꯇꯥ ꯂꯣꯒꯤꯟ ꯇꯧꯕꯤꯌꯨ",
        emailAddress: "ꯏꯃꯦꯜ ꯑꯦꯗ꯭ꯔꯦꯁ",
        password: "ꯄꯥꯁꯋꯥꯔꯗ",
        rememberMe: "ꯑꯩꯕꯨ ꯅꯤꯡꯁꯤꯡꯕꯤꯌꯨ",
        signingIn: "ꯂꯣꯒꯤꯟ ꯇꯧꯔꯤ...",
        notHaveAccount: "ꯑꯦꯀꯥꯎꯟꯠ ꯂꯩꯇꯕ꯭ꯔꯥ? ꯁꯥꯏꯟ ꯑꯞ ꯇꯧꯕꯤꯌꯨ",
        createAccount: "ꯑꯅꯧꯕꯥ ꯑꯦꯀꯥꯎꯟꯠ ꯁꯦꯝꯕꯤꯌꯨ",
        fullName: "ꯃꯤꯡ ꯄꯨꯝꯅꯃꯛ",
        confirmPassword: "ꯄꯥꯁꯋꯥꯔꯗ ꯀꯟꯐꯔꯝ ꯇꯧꯕꯤꯌꯨ",
        creatingAccount: "ꯑꯦꯀꯥꯎꯟꯠ ꯁꯦꯝꯔꯤ...",
        alreadyHaveAccount: "ꯍꯥꯟꯅꯅꯥ ꯑꯦꯀꯥꯎꯟꯠ ꯂꯩꯔꯕ꯭ꯔꯥ? ꯂꯣꯒꯤꯟ ꯇꯧꯕꯤꯌꯨ",
        or: "ꯅꯠꯇ꯭ꯔꯒꯥ"
    },
    ne: {
        welcome: "नमस्ते!",
        tagline: "आफ्नो सही जीवनसाथी खोज्नुहोस्",
        heroTitle: "आफ्नो उत्तम विवाह बायोडाटा बनाउनुहोस्",
        heroSubtitle: "प्रोफेसनल टेम्प्लेट • रियल-टाइम प्रिभ्यु • तत्काल PDF",
        startFree: "नि:शुल्क सुरु गर्नुहोस् →",
        learnMore: "थप जान्नुहोस् ↓",
        features: "सुविधाहरू",
        pricing: "मूल्य",
        signIn: "लग इन गर्नुहोस्",
        getStarted: "सुरु गर्नुहोस्",
        dashboard: "ड्यासबोर्ड",
        whyChoose: "ShadiBio किन छान्ने?",
        stunningBiodatas: "सुन्दर बायोडाटा बनाउन चाहिने सबै कुरा",
        beautifulTemplates: "सुन्दर टेम्प्लेटहरू",
        traditionalModern: "परम्परागत र आधुनिक डिजाइन",
        realTimePreview: "रियल-टाइम प्रिभ्यु",
        liveUpdates: "टाइप गर्दा प्रत्यक्ष अपडेटहरू",
        pdfDownload: "PDF डाउनलोड",
        highQualityPdfs: "उच्च-गुणस्तरका तत्काल PDF",
        privacyControls: "गोपनीयता नियन्त्रण",
        yourDataControl: "तपाईंको डाटा, तपाईंको नियन्त्रण",
        multiLanguage: "बहु-भाषा समर्थन",
        languagesSupported: "धेरै भाषाहरू समर्थित",
        smartFeatures: "स्मार्ट सुविधाहरू",
        autoCalcHistory: "अटो-क्याल्कुलेसन र संस्करण इतिहास",
        happyUsers: "सन्तुष्ट प्रयोगकर्ताहरू",
        biodatasCreated: "बायोडाटाहरू बनाइए",
        uptime: "अपटाइम",
        userRating: "प्रयोगकर्ता रेटिङ",
        pricingTitle: "सरल र स्पष्ट मूल्य",
        pricingSubtitle: "आफ्नो लागि उपयुक्त प्लान छान्नुहोस्",
        mostPopular: "सबैभन्दा लोकप्रिय",
        free: "नि:शुल्क",
        premium: "प्रिमियम",
        lifetime: "लाइफटाइम",
        forever: "सधैंको लागि",
        month: "/महिना",
        oneTime: "एक पटक",
        goPremium: "प्रिमियम लिनुहोस्",
        getLifetime: "लाइफटाइम लिनुहोस्",
        footerText: "© 2024 ShadiBio. तपाईंको सही जीवनसाथी खोज्न ❤️ सँग बनाइएको",
        privacy: "गोपनीयता",
        terms: "सर्तहरू",
        contact: "सम्पर्क",
        signInAccount: "आफ्नो खातामा लग इन गर्नुहोस्",
        emailAddress: "इमेल ठेगाना",
        password: "पासवर्ड",
        rememberMe: "मलाई सम्झनुहोस्",
        signingIn: "लग इन हुँदैछ...",
        notHaveAccount: "खाता छैन? साइन अप गर्नुहोस्",
        createAccount: "नयाँ खाता बनाउनुहोस्",
        fullName: "पूरा नाम",
        confirmPassword: "पासवर्ड सुनिश्चित गर्नुहोस्",
        creatingAccount: "खाता बन्दैछ...",
        alreadyHaveAccount: "पहिले नै खाता छ? लग इन गर्नुहोस्",
        or: "वा"
    },
    sa: {
        welcome: "नमस्ते!",
        tagline: "स्वस्य योग्यं जीवनसाथिनं अन्वेषयतु",
        heroTitle: "स्वस्य उत्तमं विवाह-बायोडाटा रचयतु",
        heroSubtitle: "व्यावसायिक टेम्पलेट्स् • वास्तविक-समयस्य पूर्वानुमानम् • त्वरितं PDF",
        startFree: "निःशुल्कं आरभताम् →",
        learnMore: "अधिकं जानातु ↓",
        features: "वैशिष्ट्यानि",
        pricing: "मौल्यम्",
        signIn: "प्रविशतु",
        getStarted: "आरभताम्",
        dashboard: "प्रबन्धकपटलं (Dashboard)",
        whyChoose: "ShadiBio किमर्थं चिनोतु?",
        stunningBiodatas: "सुन्दरबायोडाटानिर्मातुं यत् आवश्यकं तत् सर्वम्",
        beautifulTemplates: "सुन्दराणि टेम्पलेट्स्",
        traditionalModern: "पारम्परिकाः तथा आधुनिकाः आकल्पाः",
        realTimePreview: "तत्क्षणम् अवलोकनम्",
        liveUpdates: "टङ्कनसमये एव अद्यतनीकरणम्",
        pdfDownload: "PDF अवतरणम्",
        highQualityPdfs: "उच्चगुणवत्तायुक्तं त्वरितं PDF",
        privacyControls: "गोपनीयता-नियन्त्रणानि",
        yourDataControl: "भवतः दत्तांशः, भवतः नियन्त्रणम्",
        multiLanguage: "बहुभाषा-समर्थनम्",
        languagesSupported: "अनेकाः भाषाः समर्थिताः",
        smartFeatures: "विशिष्टानि वैशिष्ट्यानि",
        autoCalcHistory: "स्वयंगणना तथा संस्करणेतिहासः",
        happyUsers: "सन्तुष्टाः उपयोक्तारः",
        biodatasCreated: "निर्मितानि बायोडाटानि",
        uptime: "कार्यकालः",
        userRating: "उपयोक्तृमूल्याङ्कनम्",
        pricingTitle: "सरला तथा पारदर्शिका मूल्यव्यवस्था",
        pricingSubtitle: "भवतः कृते योग्यं योजनां चिनोतु",
        mostPopular: "सर्वाधिकं लोकप्रियम्",
        free: "निःशुल्कम्",
        premium: "प्रीमियम",
        lifetime: "आजीवनम्",
        forever: "सर्वदा",
        month: "/मासः",
        oneTime: "एकवारम्",
        goPremium: "प्रीमियम प्राप्नोतु",
        getLifetime: "आजीवनं प्राप्नोतु",
        footerText: "© 2024 ShadiBio. भवतः योग्यसाथिम् अन्वेष्टुं ❤️ इत्यनेन निर्मितम्",
        privacy: "गोपनीयता",
        terms: "नियमाः",
        contact: "सम्पर्कः",
        signInAccount: "स्वस्य खाते प्रविशतु",
        emailAddress: "ईमेल-सङ्केतः",
        password: "गुप्तसङ्केतः",
        rememberMe: "मां स्मरतु",
        signingIn: "प्रविशति...",
        notHaveAccount: "खातं नास्ति? पञ्जीकरणं करोतु",
        createAccount: "नूतनं खातं रचयतु",
        fullName: "पूर्णनाम",
        confirmPassword: "गुप्तसङ्केतं दृढीकरोतु",
        creatingAccount: "खातं निर्मीयते...",
        alreadyHaveAccount: "पूर्वतमेव खातं अस्ति? प्रविशतु",
        or: "वा"
    }`;

let contextContent = fs.readFileSync(contextPath, 'utf8');
contextContent = contextContent.replace('};\n\nexport const LanguageProvider', newTranslations + '\n};\n\nexport const LanguageProvider');
fs.writeFileSync(contextPath, contextContent);

const newLangs = \`
  const languages = [
    { code: 'en', name: 'English', flag: '🇬🇧' },
    { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
    { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
    { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
    { code: 'kn', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
    { code: 'ml', name: 'മലയാളം', flag: '🇮🇳' },
    { code: 'mr', name: 'मराठी', flag: '🇮🇳' },
    { code: 'gu', name: 'ગુજરાતી', flag: '🇮🇳' },
    { code: 'bn', name: 'বাংলা', flag: '🇮🇳' },
    { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
    { code: 'or', name: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
    { code: 'ur', name: 'اردو', flag: '🇮🇳' },
    { code: 'as', name: 'অসমীয়া', flag: '🇮🇳' },
    { code: 'mai', name: 'मैथिली', flag: '🇮🇳' },
    { code: 'sd', name: 'سنڌي', flag: '🇮🇳' },
    { code: 'kok', name: 'कोंकणी', flag: '🇮🇳' },
    { code: 'mni', name: 'ꯃꯤꯇꯩꯂꯣꯟ', flag: '🇮🇳' },
    { code: 'ne', name: 'नेपाली', flag: '🇳🇵' },
    { code: 'sa', name: 'संस्कृतम्', flag: '🇮🇳' }
  ];
\`;

let homeContent = fs.readFileSync(homePath, 'utf8');
homeContent = homeContent.replace(/const languages = \[[\s\S]*?\];/, newLangs.trim());
fs.writeFileSync(homePath, homeContent);

console.log("Translations and UI updated successfully.");
