import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        welcome: "Vaṇakkam! Namaste!",
        tagline: "FIND YOUR PERFECT MATCH",
        heroTitle: "Create Your Perfect Marriage Biodata",
        heroSubtitle: "Professional Templates • Real-time Preview • Instant PDF",
        startFree: "Start Free →",
        learnMore: "Learn More ↓",
        features: "Features",
        pricing: "Pricing",
        signIn: "Sign In",
        getStarted: "Get Started",
        dashboard: "Dashboard",
        whyChoose: "Why Choose ShadiBio?",
        stunningBiodatas: "Everything you need to create stunning biodatas",
        beautifulTemplates: "Beautiful Templates",
        traditionalModern: "Traditional & Modern designs",
        realTimePreview: "Real-time Preview",
        liveUpdates: "Live updates as you type",
        pdfDownload: "PDF Download",
        highQualityPdfs: "High-quality instant PDFs",
        privacyControls: "Privacy Controls",
        yourDataControl: "Your data, your control",
        multiLanguage: "Multi-Language",
        languagesSupported: "7+ languages supported",
        smartFeatures: "Smart Features",
        autoCalcHistory: "Auto-calc & version history",
        happyUsers: "Happy Users",
        biodatasCreated: "Biodatas Created",
        uptime: "Uptime",
        userRating: "User Rating",
        pricingTitle: "Simple, Transparent Pricing",
        pricingSubtitle: "Choose the plan that works for you",
        mostPopular: "MOST POPULAR",
        free: "Free",
        premium: "Premium",
        lifetime: "Lifetime",
        forever: "Forever",
        month: "/month",
        oneTime: "One-time",
        goPremium: "Go Premium",
        getLifetime: "Get Lifetime",
        footerText: "© 2024 ShadiBio. Made with ❤️ for finding your perfect match",
        privacy: "Privacy",
        terms: "Terms",
        contact: "Contact",
        signInAccount: "Sign in to your account",
        emailAddress: "Email address",
        password: "Password",
        rememberMe: "Remember me",
        signingIn: "Signing in...",
        notHaveAccount: "Don't have an account? Sign up",
        createAccount: "Create a new account",
        fullName: "Full Name",
        confirmPassword: "Confirm Password",
        creatingAccount: "Creating account...",
        alreadyHaveAccount: "Already have an account? Sign in",
        or: "Or"
    },
    hi: {
        welcome: "नमस्ते!",
        tagline: "अपना आदर्श जीवनसाथी खोजें",
        heroTitle: "अपनी बेहतरीन शादी का बायोडाटा बनाएं",
        heroSubtitle: "प्रोफेशनल टेम्पलेट • रियल-टाइम प्रीव्यू • इंस्टेंट पीडीएफ",
        startFree: "मुफ्त में शुरू करें →",
        learnMore: "और जानें ↓",
        features: "विशेषताएं",
        pricing: "कीमत",
        signIn: "लॉग इन करें",
        getStarted: "शुरू करें",
        dashboard: "डैशबोर्ड",
        whyChoose: "ShadiBio क्यों चुनें?",
        stunningBiodatas: "शानदार बायोडाटा बनाने के लिए सब कुछ जो आपको चाहिए",
        beautifulTemplates: "खूबसूरत टेम्पलेट्स",
        traditionalModern: "पारंपरिक और आधुनिक डिजाइन",
        realTimePreview: "रियल-टाइम प्रीव्यू",
        liveUpdates: "टाइप करते ही लाइव अपडेट",
        pdfDownload: "पीडीएफ डाउनलोड",
        highQualityPdfs: "उच्च गुणवत्ता वाले इंस्टेंट पीडीएफ",
        privacyControls: "गोपनीयता नियंत्रण",
        yourDataControl: "आपका डेटा, आपका नियंत्रण",
        multiLanguage: "बहु-भाषी",
        languagesSupported: "7+ भाषाएं समर्थित",
        smartFeatures: "स्मार्ट फीचर्स",
        autoCalcHistory: "ऑटो-कैलकुलेशन और वर्जन हिस्ट्री",
        happyUsers: "खुश उपयोगकर्ता",
        biodatasCreated: "बायोडाटा बनाए गए",
        uptime: "अपटाइम",
        userRating: "उपयोगकर्ता रेटिंग",
        pricingTitle: "सरल और पारदर्शी कीमतें",
        pricingSubtitle: "वह प्लान चुनें जो आपके लिए सही हो",
        mostPopular: "सबसे लोकप्रिय",
        free: "मुफ्त",
        premium: "प्रीमियम",
        lifetime: "लाइफटाइम",
        forever: "हमेशा के लिए",
        month: "/महीना",
        oneTime: "एक बार",
        goPremium: "प्रीमियम लें",
        getLifetime: "लाइफटाइम लें",
        footerText: "© 2024 ShadiBio. आपके आदर्श जीवनसाथी को खोजने के लिए ❤️ से बनाया गया",
        privacy: "गोपनीयता",
        terms: "नियम",
        contact: "संपर्क",
        signInAccount: "अपने खाते में लॉग इन करें",
        emailAddress: "ईमेल पता",
        password: "पासवर्ड",
        rememberMe: "मुझे याद रखें",
        signingIn: "लॉग इन हो रहा है...",
        notHaveAccount: "खाता नहीं है? साइन अप करें",
        createAccount: "एक नया खाता बनाएं",
        fullName: "पूरा नाम",
        confirmPassword: "पासवर्ड की पुष्टि करें",
        creatingAccount: "खाता बनाया जा रहा है...",
        alreadyHaveAccount: "पहले से खाता है? लॉग इन करें",
        or: "या"
    },
    ta: {
        welcome: "வணக்கம்!",
        tagline: "உங்கள் சரியான துணையை கண்டறியவும்",
        heroTitle: "உங்கள் சரியான திருமண பயோடேட்டாவை உருவாக்குங்கள்",
        heroSubtitle: "தொழில்முறை வார்ப்புருக்கள் • நிகழ்நேர முன்னோட்டம் • உடனடி PDF",
        startFree: "இலவசமாகத் தொடங்குங்கள் →",
        learnMore: "மேலும் அறிய ↓",
        features: "அம்சங்கள்",
        pricing: "விலை",
        signIn: "உள்நுழைக",
        getStarted: "தொடங்குங்கள்",
        dashboard: "டாஷ்போர்டு",
        whyChoose: "ஏன் ShadiBio தேர்ந்தெடுக்க வேண்டும்?",
        stunningBiodatas: "அற்புதமான பயோடேட்டாவை உருவாக்க உங்களுக்கு தேவையான அனைத்தும்",
        beautifulTemplates: "அழகான வார்ப்புருக்கள்",
        traditionalModern: "பாரம்பரிய மற்றும் நவீன வடிவமைப்புகள்",
        realTimePreview: "நிகழ்நேர முன்னோட்டம்",
        liveUpdates: "நீங்கள் தட்டச்சு செய்யும் போது நேரடி அறிவிப்புகள்",
        pdfDownload: "PDF பதிவிறக்கம்",
        highQualityPdfs: "உயர்தர உடனடி PDF-கள்",
        privacyControls: "தனியுரிமை கட்டுப்பாடுகள்",
        yourDataControl: "உங்கள் தரவு, உங்கள் கட்டுப்பாடு",
        multiLanguage: "பல மொழி ஆதரவு",
        languagesSupported: "7+ மொழிகள் ஆதரிக்கப்படுகின்றன",
        smartFeatures: "ஸ்மார்ட் அம்சங்கள்",
        autoCalcHistory: "தானியங்கி கணக்கீடு மற்றும் பதிப்பு வரலாறு",
        happyUsers: "மகிழ்ச்சியான பயனர்கள்",
        biodatasCreated: "பயோடேட்டாக்கள் உருவாக்கப்பட்டன",
        uptime: "செயல்பாட்டு நேரம்",
        userRating: "பயனர் மதிப்பீடு",
        pricingTitle: "எளிமையான, வெளிப்படையான விலை",
        pricingSubtitle: "உங்களுக்கு ஏற்ற திட்டத்தைத் தேர்ந்தெடுக்கவும்",
        mostPopular: "மிகவும் பிரபலமானது",
        free: "இலவசம்",
        premium: "பிரீமியம்",
        lifetime: "வாழ்நாள்",
        forever: "எப்போதும்",
        month: "/மாதம்",
        oneTime: "ஒரு முறை",
        goPremium: "பிரீமியம் பெறுங்கள்",
        getLifetime: "வாழ்நாள் அணுகல் பெறுங்கள்",
        footerText: "© 2024 ShadiBio. உங்கள் சரியான துணையை கண்டறிய ❤️ உடன் உருவாக்கப்பட்டது",
        privacy: "தனியுரிமை",
        terms: "நிபந்தனைகள்",
        contact: "தொடர்பு",
        signInAccount: "உங்கள் கணக்கில் உள்நுழைக",
        emailAddress: "மின்னஞ்சல் முகவரி",
        password: "கடவுச்சொல்",
        rememberMe: "என்னை நினைவில் கொள்க",
        signingIn: "உள்நுழைகிறது...",
        notHaveAccount: "கணக்கு இல்லையா? பதிவு செய்க",
        createAccount: "புதிய கணக்கை உருவாக்கவும்",
        fullName: "முழு பெயர்",
        confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
        creatingAccount: "கணக்கு உருவாக்கப்படுகிறது...",
        alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக",
        or: "அல்லது"
    },
    te: {
        welcome: "నమస్కారం!",
        tagline: "మీ పరిపూర్ణ తోడును కనుగొనండి",
        heroTitle: "మీ పరిపూర్ణ వివాహ బయోడేటాను సృష్టించండి",
        heroSubtitle: "ప్రొఫెషనల్ టెంప్లేట్లు • రియల్-టైమ్ ప్రివ్యూ • ఇన్స్టంట్ PDF",
        startFree: "ఉచితంగా ప్రారంభించండి →",
        learnMore: "మరింత తెలుసుకోండి ↓",
        features: "ఫీచర్లు",
        pricing: "ధర",
        signIn: "లాగిన్ అవ్వండి",
        getStarted: "ప్రారంభించండి",
        dashboard: "డ్యాష్ బోర్డ్",
        whyChoose: "ShadiBioని ఎందుకు ఎంచుకోవాలి?",
        stunningBiodatas: "అద్భుతమైన బయోడేటాను సృష్టించడానికి మీకు కావలసినవన్నీ",
        beautifulTemplates: "అందమైన టెంప్లేట్లు",
        traditionalModern: "సాంప్రదాయ మరియు ఆధునిక డిజైన్లు",
        realTimePreview: "రియల్-టైమ్ ప్రివ్యూ",
        liveUpdates: "మీరు టైప్ చేస్తున్నప్పుడు లైవ్ అప్డేట్లు",
        pdfDownload: "PDF డౌన్లోడ్",
        highQualityPdfs: "అధిక నాణ్యత గల ఇన్స్టంట్ PDFలు",
        privacyControls: "గోప్యత నియంత్రణలు",
        yourDataControl: "మీ డేటా, మీ నియంత్రణ",
        multiLanguage: "బహుభాషా మద్దతు",
        languagesSupported: "7+ భాషలకు మద్దతు",
        smartFeatures: "స్మార్ట్ ఫీచర్లు",
        autoCalcHistory: "ఆటో-కాలిక్యులేషన్ మరియు వెర్షన్ చరిత్ర",
        happyUsers: "సంతోషకరమైన వినియోగదారులు",
        biodatasCreated: "లిఖించబడిన బయోడేటాలు",
        uptime: "అప్ టైమ్",
        userRating: "వినియోగదారు రేటింగ్",
        pricingTitle: "సరళమైన, పారదర్శకమైన ధర",
        pricingSubtitle: "మీకు సరిపోయే ప్లాన్ ను ఎంచుకోండి",
        mostPopular: "అత్యంత ప్రజాదరణ పొందినది",
        free: "ఉచితం",
        premium: "ప్రీమియం",
        lifetime: "జీవితకాలం",
        forever: "ఎప్పటికీ",
        month: "/నెల",
        oneTime: "ఒక సారి",
        goPremium: "ప్రీమియం పొందండి",
        getLifetime: "జీవితకాలం పొందండి",
        footerText: "© 2024 ShadiBio. మీ పరిపూర్ణ తోడును కనుగొనడానికి ❤️ తో తయారు చేయబడింది",
        privacy: "గోప్యత",
        terms: "నిబంధనలు",
        contact: "సంప్రదించండి",
        signInAccount: "మీ ఖాతాలోకి లాగిన్ అవ్వండి",
        emailAddress: "ఈమెయిల్ చిరునామా",
        password: "పాస్వర్డ్",
        rememberMe: "నన్ను గుర్తుంచుకో",
        signingIn: "లాగిన్ అవుతోంది...",
        notHaveAccount: "ఖాతా లేదా? సైన్ అప్ చేయండి",
        createAccount: "కొత్త ఖాతాను సృష్టించండి",
        fullName: "పూర్తి పేరు",
        confirmPassword: "పాస్వర్డ్ను నిర్ధారించండి",
        creatingAccount: "ఖాతా సృష్టించబడుతోంది...",
        alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వండి",
        or: "లేదా"
    },
    kn: {
        welcome: "ನಮಸ್ಕಾರ!",
        tagline: "ನಿಮ್ಮ ಪರಿಪೂರ್ಣ ಜೀವನ ಸಂಗಾತಿಯನ್ನು ಹುಡುಕಿ",
        heroTitle: "ನಿಮ್ಮ ಪರಿಪೂರ್ಣ ವಿವಾಹದ ಬಯೋಡಾಟಾವನ್ನು ರಚಿಸಿ",
        heroSubtitle: "ವೃತ್ತಿಪರ ಟೆಂಪ್ಲೇಟ್‌ಗಳು • ರಿಯಲ್-ಟೈಮ್ ಪ್ರಿವ್ಯೂ • ಇನ್‌ಸ್ಟಂಟ್ PDF",
        startFree: "ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ →",
        learnMore: "ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ ↓",
        features: "ವೈಶಿಷ್ಟ್ಯಗಳು",
        pricing: "ಬೆಲೆ",
        signIn: "ಲಾಗಿನ್ ಮಾಡಿ",
        getStarted: "ಪ್ರಾರಂಭಿಸಿ",
        dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        whyChoose: "ShadiBio ಏಕೆ ಆರಿಸಬೇಕು?",
        stunningBiodatas: "ಅದ್ಭುತ ಬಯೋಡಾಟಾವನ್ನು ರಚಿಸಲು ನಿಮಗೆ ಬೇಕಾದ ಎಲ್ಲವೂ ಇಲ್ಲಿದೆ",
        beautifulTemplates: "ಸುಂದರವಾದ ಟೆಂಪ್ಲೇಟ್‌ಗಳು",
        traditionalModern: "ಸಾಂಪ್ರದಾಯಿಕ ಮತ್ತು ಆಧುನಿಕ ವಿನ್ಯಾಸಗಳು",
        realTimePreview: "ರಿಯಲ್-ಟೈಮ್ ಪ್ರಿವ್ಯೂ",
        liveUpdates: "ನೀವು ಟೈಪ್ ಮಾಡುವಾಗಲೇ ಲೈವ್ ಅಪ್‌ಡೇಟ್‌ಗಳು",
        pdfDownload: "PDF ಡೌನ್‌ಲೋಡ್",
        highQualityPdfs: "ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಇನ್‌ಸ್ಟಂಟ್ PDFಗಳು",
        privacyControls: "ಗೌಪ್ಯತೆ ನಿಯಂತ್ರಣಗಳು",
        yourDataControl: "ನಿಮ್ಮ ಡೇಟಾ, ನಿಮ್ಮ ನಿಯಂತ್ರಣ",
        multiLanguage: "ಬಹುಭಾಷಾ ಬೆಂಬಲ",
        languagesSupported: "7+ ಭಾಷೆಗಳಿಗೆ ಬೆಂಬಲ",
        smartFeatures: "ಸ್ಮಾರ್ಟ್ ವೈಶಿಷ್ಟ್ಯಗಳು",
        autoCalcHistory: "ಆಟೋ-ಕ್ಯಾಲ್ಕುಲೇಷನ್ ಮತ್ತು ವರ್ಷನ್ ಹಿಸ್ಟರಿ",
        happyUsers: "ಸಂತೋಷದ ಬಳಕೆದಾರರು",
        biodatasCreated: "ಬಯೋಡಾಟಾಗಳನ್ನು ರಚಿಸಲಾಗಿದೆ",
        uptime: "ಅಪ್‌ಟೈಮ್",
        userRating: "ಬಳಕೆದಾರರ ರೇಟಿಂಗ್",
        pricingTitle: "ಸರಳ ಮತ್ತು ಪಾರದರ್ಶಕ ಬೆಲೆ",
        pricingSubtitle: "ನಿಮಗಾಗಿ ಸೂಕ್ತವಾದ ಪ್ಲಾನ್ ಆರಿಸಿ",
        mostPopular: "ಅತ್ಯಂತ ಜನಪ್ರಿಯ",
        free: "ಉಚಿತ",
        premium: "ಪ್ರೀಮಿಯಂ",
        lifetime: "ಲೈಫ್‌ಟೈಮ್",
        forever: "ಯಾವಾಗಲೂ",
        month: "/ತಿಂಗಳು",
        oneTime: "ಒಂದು ಬಾರಿ",
        goPremium: "ಪ್ರೀಮಿಯಂ ಪಡೆರಿ",
        getLifetime: "ಲೈಫ್‌ಟೈಮ್ ಪಡೆರಿ",
        footerText: "© 2024 ShadiBio. ನಿಮ್ಮ ಪರಿಪೂರ್ಣ ಸಂಗಾತಿಯನ್ನು ಹುಡುಕಲು ❤️ ಇಂದ ತಯಾರಿಸಲಾಗಿದೆ",
        privacy: "ಗೌಪ್ಯತೆ",
        terms: "ನಿಯಮಗಳು",
        contact: "ಸಂಪರ್ಕಿಸಿ",
        signInAccount: "ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ",
        emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
        password: "ಪಾಸ್‌ವರ್ಡ್",
        rememberMe: "ನನ್ನನ್ನು ನೆನಪಿಡಿ",
        signingIn: "ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...",
        notHaveAccount: "ಖಾತೆ ಇಲ್ಲವೇ? ಸೈನ್ ಅಪ್ ಮಾಡಿ",
        createAccount: "ಹೊಸ ಖಾತೆಯನ್ನು ರಚಿಸಿ",
        fullName: "ಪೂರ್ಣ ಹೆಸರು",
        confirmPassword: "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
        creatingAccount: "ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...",
        alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ",
        or: "ಅಥವಾ"
    },
    ml: {
        welcome: "നമസ്കാരം!",
        tagline: "നിങ്ങളുടെ അനുയോജ്യമായ ജീവിത പങ്കാളിയെ കണ്ടെത്തുക",
        heroTitle: "നിങ്ങളുടെ മികച്ച വിവാഹ ബയോഡാറ്റ സൃഷ്ടിക്കുക",
        heroSubtitle: "പ്രൊഫഷണൽ ടെംപ്ലേറ്റുകൾ • തത്സമയ പ്രിവ്യൂ • ഇൻസ്റ്റന്റ് PDF",
        startFree: "സൗജന്യമായി ആരംഭിക്കുക →",
        learnMore: "കൂടുതൽ അറിയാൻ ↓",
        features: "ഫീച്ചറുകൾ",
        pricing: "വില",
        signIn: "ലോഗിൻ ചെയ്യുക",
        getStarted: "ആരംഭിക്കുക",
        dashboard: "ഡാഷ്‌ബോർഡ്",
        whyChoose: "എന്തുകൊണ്ട് ShadiBio തിരഞ്ഞെടുക്കണം?",
        stunningBiodatas: "മനോഹരമായ ബയോഡാറ്റ സൃഷ്ടിക്കാൻ നിങ്ങൾക്ക് ആവശ്യമുള്ളതെല്ലാം",
        beautifulTemplates: "മനോഹരമായ ടെംപ്ലേറ്റുകൾ",
        traditionalModern: "പരമ്പരാഗതവും ആധുനികവുമായ ഡിസൈനുകൾ",
        realTimePreview: "തത്സമയ പ്രിവ്യൂ",
        liveUpdates: "നിങ്ങൾ ടൈപ്പ് ചെയ്യുമ്പോൾ തന്നെ തത്സമയ അപ്‌ഡേറ്റുകൾ",
        pdfDownload: "PDF ഡൗൺലോഡ്",
        highQualityPdfs: "ഉയർന്ന നിലവാരമുള്ള ഇൻസ്റ്റന്റ് PDF-കൾ",
        privacyControls: "സ്വകാര്യതാ നിയന്ത്രണങ്ങൾ",
        yourDataControl: "നിങ്ങളുടെ ഡാറ്റ, നിങ്ങളുടെ നിയന്ത്രണം",
        multiLanguage: "ബഹുഭാഷാ പിന്തുണ",
        languagesSupported: "7+ ഭാഷകൾ പിന്തുണയ്ക്കുന്നു",
        smartFeatures: "സ്മാർട്ട് ഫീച്ചറുകൾ",
        autoCalcHistory: "ഓട്ടോ-കാൽക്കുലേഷൻ & പതിപ്പ് ചരിത്രം",
        happyUsers: "സന്തോഷവാന്മാരായ ഉപയോക്താക്കൾ",
        biodatasCreated: "സൃഷ്ടിച്ച ബയോഡാറ്റകൾ",
        uptime: "അപ്‌ടൈം",
        userRating: "ഉപയോക്തൃ റേറ്റിംഗ്",
        pricingTitle: "ലളിതവും സുതാര്യവുമായ വില",
        pricingSubtitle: "നിങ്ങൾക്ക് അനുയോജ്യമായ പ്ലാൻ തിരഞ്ഞെടുക്കുക",
        mostPopular: "ഏറ്റവും ജനപ്രിയം",
        free: "സൗജന്യം",
        premium: "പ്രീമിയം",
        lifetime: "ലൈഫ് ടൈം",
        forever: "എന്നെന്നേക്കുമായി",
        month: "/മാസം",
        oneTime: "ഒറ്റത്തവണ",
        goPremium: "പ്രീമിയം നേടുക",
        getLifetime: "ലൈഫ് ടൈം നേടുക",
        footerText: "© 2024 ShadiBio. അനുയോജ്യമായ പങ്കാളിയെ കണ്ടെത്താൻ ❤️ കൂടെ നിർമ്മിച്ചത്",
        privacy: "സ്വകാര്യത",
        terms: "നിബന്ധനകൾ",
        contact: "ബന്ധപ്പെടുക",
        signInAccount: "നിങ്ങളുടെ അക്കൗണ്ടിലേക്ക് ലോഗിൻ ചെയ്യുക",
        emailAddress: "ഇമെയിൽ വിലാസം",
        password: "പാസ്‌വേഡ്",
        rememberMe: "എന്നെ ഓർമ്മിക്കുക",
        signingIn: "ലോഗിൻ ചെയ്യുന്നു...",
        notHaveAccount: "അക്കൗണ്ട് ഇല്ലേ? സൈൻ അപ്പ് ചെയ്യുക",
        createAccount: "പുതിയ അക്കൗണ്ട് സൃഷ്ടിക്കുക",
        fullName: "മുഴുവൻ പേര്",
        confirmPassword: "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
        creatingAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു...",
        alreadyHaveAccount: "നിലവിൽ അക്കൗണ്ട് ഉണ്ടോ? ലോഗിൻ ചെയ്യുക",
        or: "അല്ലെങ്കിൽ"
    },
    mr: {
        welcome: "नमस्कार!",
        tagline: "तुमचा योग्य जोडीदार शोधा",
        heroTitle: "तुमचा परिपूर्ण विवाह बायोडाटा तयार करा",
        heroSubtitle: "व्यावसायिक टेम्पलेट्स • रिअल-टाइम प्रिव्हयू • झटपट PDF",
        startFree: "मोफत सुरू करा →",
        learnMore: "अधिक जाणून घ्या ↓",
        features: "वैशिष्ट्ये",
        pricing: "किंमत",
        signIn: "लॉग इन करा",
        getStarted: "सुरू करा",
        dashboard: "डॅशबोर्ड",
        whyChoose: "ShadiBio का निवडावे?",
        stunningBiodatas: "आकर्षक बायोडाटा तयार करण्यासाठी तुम्हाला आवश्यक असलेले सर्व काही",
        beautifulTemplates: "सुंदर टेम्पलेट्स",
        traditionalModern: "पारंपारिक आणि आधुनिक डिझाईन्स",
        realTimePreview: "रिअल-टाइम प्रिव्हयू",
        liveUpdates: "तुम्ही टाईप करताच लाईव्ह अपडेट्स",
        pdfDownload: "PDF डाउनलोड",
        highQualityPdfs: "उच्च-गुणवत्तेची झटपट PDF",
        privacyControls: "गोपनीयता नियंत्रणे",
        yourDataControl: "तुमचा डेटा, तुमचे नियंत्रण",
        multiLanguage: "बहुभाषिक",
        languagesSupported: "१२+ भाषा समर्थित",
        smartFeatures: "स्मार्ट वैशिष्ट्ये",
        autoCalcHistory: "ऑटो-कॅलक्युलेशन आणि आवृत्ती इतिहास",
        happyUsers: "आनंदी वापरकर्ते",
        biodatasCreated: "बायोडाटा तयार केले",
        uptime: "अपटाइम",
        userRating: "वापरकर्ता रेटिंग",
        pricingTitle: "सोपी आणि पारदर्शक किंमत",
        pricingSubtitle: "तुमच्यासाठी योग्य अशी योजना निवडा",
        mostPopular: "सर्वाधिक लोकप्रिय",
        free: "मोफत",
        premium: "प्रीमियम",
        lifetime: "आजीवन",
        forever: "कायमचे",
        month: "/महिना",
        oneTime: "एकदा",
        goPremium: "प्रीमियम मिळवा",
        getLifetime: "आजीवन मिळवा",
        footerText: "© २०२४ ShadiBio. तुमचा योग्य जोडीदार शोधण्यासाठी ❤️ ने बनवले आहे",
        privacy: "गोपनीयता",
        terms: "अटी",
        contact: "संपर्क",
        signInAccount: "तुमच्या खात्यात लॉग इन करा",
        emailAddress: "ईमेल पत्ता",
        password: "पासवर्ड",
        rememberMe: "मला लक्षात ठेवा",
        signingIn: "लॉग इन होत आहे...",
        notHaveAccount: "खाते नाही? साइन अप करा",
        createAccount: "नवीन खाते तयार करा",
        fullName: "पूर्ण नाव",
        confirmPassword: "पासवर्डची पुष्टी करा",
        creatingAccount: "खाते तयार होत आहे...",
        alreadyHaveAccount: "आधीपासून खाते आहे? लॉग इन करा",
        or: "किंवा"
    },
    bn: {
        welcome: "নমস্কার!",
        tagline: "আপনার সঠিক জীবনসঙ্গী খুঁজুন",
        heroTitle: "আপনার নিখুঁত বিয়ের বায়োডাটা তৈরি করুন",
        heroSubtitle: "পেশাদার টেমপ্লেট • রিয়েল-টাইম প্রিভিউ • তাৎক্ষণিক PDF",
        startFree: "বিনামূল্যে শুরু করুন →",
        learnMore: "আরও জানুন ↓",
        features: "বৈশিষ্ট্য",
        pricing: "মূল্য নির্ধারণ",
        signIn: "লগ ইন করুন",
        getStarted: "শুরু করুন",
        dashboard: "ড্যাশবোর্ড",
        whyChoose: "কেন ShadiBio বেছে নেবেন?",
        stunningBiodatas: "অত্যাশ্চর্য বায়োডাটা তৈরি করার জন্য আপনার যা যা প্রয়োজন",
        beautifulTemplates: "সুন্দর টেমপ্লেট",
        traditionalModern: "ঐতিহ্যবাহী এবং আধুনিক ডিজাইন",
        realTimePreview: "রিয়েল-টাইম প্রিভিউ",
        liveUpdates: "টাইপ করার সাথে সাথে লাইভ আপডেট",
        pdfDownload: "PDF ডাউনলোড",
        highQualityPdfs: "উচ্চ মানের ইনস্ট্যান্ট PDF",
        privacyControls: "গোপনীয়তা নিয়ন্ত্রণ",
        yourDataControl: "আপনার ডেটা, আপনার নিয়ন্ত্রণ",
        multiLanguage: "বহুভাষী",
        languagesSupported: "১২+ ভাষা সমর্থিত",
        smartFeatures: "স্মার্ট বৈশিষ্ট্য",
        autoCalcHistory: "অটো-ক্যালকুলেশন এবং সংস্করণ ইতিহাস",
        happyUsers: "সন্তুষ্ট ব্যবহারকারী",
        biodatasCreated: "বায়োডাটা তৈরি করা হয়েছে",
        uptime: "আপটাইম",
        userRating: "ব্যবহারকারীর রেটিং",
        pricingTitle: "সহজ এবং স্বচ্ছ মূল্য",
        pricingSubtitle: "আপনার জন্য উপযুক্ত একটি পরিকল্পনা চয়ন করুন",
        mostPopular: "সবচেয়ে জনপ্রিয়",
        free: "বিনামূল্যে",
        premium: "প্রিমিয়াম",
        lifetime: "আজীবন",
        forever: "চিরকালের জন্য",
        month: "/মাস",
        oneTime: "একবার",
        goPremium: "প্রিমিয়াম নিন",
        getLifetime: "আজীবন অ্যাক্সেস নিন",
        footerText: "© ২০২৪ ShadiBio. আপনার নিখুঁত সঙ্গী খুঁজে পাওয়ার জন্য ❤️ দিয়ে তৈরি",
        privacy: "গোপনীয়তা",
        terms: "শর্তাবলী",
        contact: "যোগাযোগ",
        signInAccount: "আপনার অ্যাকাউন্টে লগ ইন করুন",
        emailAddress: "ইমেল ঠিকানা",
        password: "পাসওয়ার্ড",
        rememberMe: "আমাকে মনে রাখুন",
        signingIn: "লগ ইন করা হচ্ছে...",
        notHaveAccount: "অ্যাকাউন্ট নেই? সাইন আপ করুন",
        createAccount: "নতুন অ্যাকাউন্ট তৈরি করুন",
        fullName: "পুরো নাম",
        confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
        creatingAccount: "অ্যাকাউন্ট তৈরি করা হচ্ছে...",
        alreadyHaveAccount: "আগে থেকেই অ্যাকাউন্ট আছে? লগ ইন করুন",
        or: "বা"
    },
    gu: {
        welcome: "નમસ્તે!",
        tagline: "તમારો આદર્શ જીવનસાથી શોધો",
        heroTitle: "તમારો પરફેક્ટ લગ્નનો બાયોડેટા બનાવો",
        heroSubtitle: "પ્રોફેશનલ ટેમ્પ્લેટ્સ • રિયલ-ટાઇમ પ્રિવ્યૂ • ઇન્સ્ટન્ટ PDF",
        startFree: "મફત શરૂ કરો →",
        learnMore: "વધુ જાણો ↓",
        features: "સુવિધાઓ",
        pricing: "કિંમત",
        signIn: "લૉગ ઇન કરો",
        getStarted: "શરૂ કરો",
        dashboard: "ડેશબોર્ડ",
        whyChoose: "ShadiBio કેમ પસંદ કરવું?",
        stunningBiodatas: "આકર્ષક બાયોડેટા બનાવવા માટે તમને જેની જરૂર છે તે બધું",
        beautifulTemplates: "સુંદર ટેમ્પ્લેટ્સ",
        traditionalModern: "પરંપરાગત અને આધુનિક ડિઝાઇન",
        realTimePreview: "રિયલ-ટાઇમ પ્રિવ્યૂ",
        liveUpdates: "તમે ટાઇપ કરો તેમ લાઇવ અપડેટ્સ",
        pdfDownload: "PDF ડાઉનલોડ",
        highQualityPdfs: "ઉચ્ચ-ગુણવત્તાવાળી ઇન્સ્ટન્ટ PDF",
        privacyControls: "ગોપનીયતા નિયંત્રણો",
        yourDataControl: "તમારો ડેટા, તમારું નિયંત્રણ",
        multiLanguage: "બહુભાષી",
        languagesSupported: "૧૨+ ભાષાઓ સમર્થિત",
        smartFeatures: "સ્માર્ટ સુવિધાઓ",
        autoCalcHistory: "ઑટો-કેલ્ક્યુલેશન અને સંસ્કરણ ઇતિહાસ",
        happyUsers: "ખુશ વપરાશકર્તાઓ",
        biodatasCreated: "બાયોડેટા બનાવ્યા",
        uptime: "અપટાઇમ",
        userRating: "વપરાશકર્તા રેટિંગ",
        pricingTitle: "સરળ અને પારદર્શક કિંમત",
        pricingSubtitle: "તમારા માટે યોગ્ય પ્લાન પસંદ કરો",
        mostPopular: "સૌથી વધુ લોકપ્રિય",
        free: "મફત",
        premium: "પ્રીમિયમ",
        lifetime: "આજીવન",
        forever: "કાયમ માટે",
        month: "/મહિનો",
        oneTime: "એકવાર",
        goPremium: "પ્રીમિયમ મેળવો",
        getLifetime: "આજીવન મેળવો",
        footerText: "© ૨૦૨૪ ShadiBio. તમારા આદર્શ જીવનસાથી શોધવા માટે ❤️ થી બનાવવામાં આવ્યું છે",
        privacy: "ગોપનીયતા",
        terms: "શરતો",
        contact: "સંપર્ક",
        signInAccount: "તમારા એકાઉન્ટમાં લૉગ ઇન કરો",
        emailAddress: "ઇમેઇલ સરનામું",
        password: "પાસવર્ડ",
        rememberMe: "મને યાદ રાખો",
        signingIn: "લૉગ ઇન થઈ રહ્યું છે...",
        notHaveAccount: "એકાઉન્ટ નથી? સાઇન અપ કરો",
        createAccount: "નવું એકાઉન્ટ બનાવો",
        fullName: "પૂરું નામ",
        confirmPassword: "પાસવર્ડની પુષ્ટિ કરો",
        creatingAccount: "એકાઉન્ટ બની રહ્યું છે...",
        alreadyHaveAccount: "પહેલેથી જ એકાઉન્ટ છે? લૉગ ઇન કરો",
        or: "અથવા"
    },
    pa: {
        welcome: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ!",
        tagline: "ਆਪਣਾ ਸਹੀ ਜੀਵਨ ਸਾਥੀ ਲੱਭੋ",
        heroTitle: "ਆਪਣਾ ਪੂਰਾ ਵਿਆਹ ਬਾਇਓਡਾਟਾ ਬਣਾਓ",
        heroSubtitle: "ਪੇਸ਼ੇਵਰ ਟੈਂਪਲੇਟਸ • ਰੀਅਲ-ਟਾਈਮ ਪ੍ਰੀਵਿਊ • ਤੁਰੰਤ PDF",
        startFree: "ਮੁਫ਼ਤ ਸ਼ੁਰੂ ਕਰੋ →",
        learnMore: "ਹੋਰ ਜਾਣੋ ↓",
        features: "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
        pricing: "ਕੀਮਤ",
        signIn: "ਲਾਗੂ ਕਰੋ",
        getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
        dashboard: "ਡੈਸ਼ਬੋਰਡ",
        whyChoose: "ShadiBio ਕਿਉਂ ਚੁਣੋ?",
        stunningBiodatas: "ਸ਼ਾਨਦਾਰ ਬਾਇਓਡਾਟਾ ਬਣਾਉਣ ਲਈ ਤੁਹਾਨੂੰ ਜੋ ਵੀ ਚਾਹੀਦਾ ਹੈ",
        beautifulTemplates: "ਸੁੰਦਰ ਟੈਂਪਲੇਟਸ",
        traditionalModern: "ਰਵਾਇਤੀ ਅਤੇ ਆਧੁਨਿਕ ਡਿਜ਼ਾਈਨ",
        realTimePreview: "ਰੀਅਲ-ਟਾਈਮ ਪ੍ਰੀਵਿਊ",
        liveUpdates: "ਜਿਵੇਂ ਤੁਸੀਂ ਟਾਈਪ ਕਰਦੇ ਹੋ ਲਾਈਵ ਅੱਪਡੇਟ",
        pdfDownload: "PDF ਡਾਊਨਲੋਡ",
        highQualityPdfs: "ਉੱਚ-ਗੁਣਵੱਤਾ ਵਾਲੀ ਤੁਰੰਤ PDF",
        privacyControls: "ਗੋਪਨੀਯਤਾ ਨਿਯੰਤਰਣ",
        yourDataControl: "ਤੁਹਾਡਾ ਡੇਟਾ, ਤੁਹਾਡਾ ਨਿਯੰਤਰਣ",
        multiLanguage: "ਬਹੁ-ਭਾਸ਼ਾਈ",
        languagesSupported: "੧੨+ ਭਾਸ਼ਾਵਾਂ ਸਮਰਥਿਤ",
        smartFeatures: "ਸਮਾਰਟ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
        autoCalcHistory: "ਆਟੋ-ਕੈਲਕੂਲੇਸ਼ਨ ਐਂਡ ਵਰਜਨ ਅਤੀਤ",
        happyUsers: "ਖੁਸ਼ ਉਪਭੋਗਤਾ",
        biodatasCreated: "ਬਾਇਓਡਾਟਾ ਬਣਾਏ ਗਏ",
        uptime: "ਅਪਟਾਈਮ",
        userRating: "ਉਪਭੋਗਤਾ ਰੇਟਿੰਗ",
        pricingTitle: "ਸਰਲ, ਪਾਰਦਰਸ਼ੀ ਕੀਮਤ",
        pricingSubtitle: "ਉਹ ਯੋਜਨਾ ਚੁਣੋ ਜੋ ਤੁਹਾਡੇ ਲਈ ਸਹੀ ਹੋਵੇ",
        mostPopular: "ਸਭ ਤੋਂ ਵੱਧ ਪ੍ਰਸਿੱਧ",
        free: "ਮੁਫ਼ਤ",
        premium: "ਪ੍ਰੀਮੀਅਮ",
        lifetime: "ਉਮਰ ਭਰ",
        forever: "ਹਮੇਸ਼ਾ ਲਈ",
        month: "/ਮਹੀਨਾ",
        oneTime: "ਇਕ ਵਾਰ",
        goPremium: "ਪ੍ਰੀਮੀਅਮ ਲਵੋ",
        getLifetime: "ਲਾਈਫਟਾਈਮ ਲਵੋ",
        footerText: "© ੨੦੨੪ ShadiBio. ਤੁਹਾਡਾ ਸਹੀ ਸਾਥੀ ਲੱਭਣ ਲਈ ❤️ ਨਾਲ ਬਣਾਇਆ ਗਿਆ",
        privacy: "ਗੋਪਨੀਯਤਾ",
        terms: "ਸ਼ਰਤਾਂ",
        contact: "ਸੰਪਰਕ",
        signInAccount: "ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ",
        emailAddress: "ਈਮੇਲ ਪਤਾ",
        password: "ਪਾਸਵਰਡ",
        rememberMe: "ਮੈਨੂੰ ਯਾਦ ਰੱਖੋ",
        signingIn: "ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...",
        notHaveAccount: "ਕੀ ਖਾਤਾ ਨਹੀਂ ਹੈ? ਸਾਈਨ ਅੱਪ ਕਰੋ",
        createAccount: "ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ",
        fullName: "ਪੂਰਾ ਨਾਮ",
        confirmPassword: "ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
        creatingAccount: "ਖਾਤਾ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...",
        alreadyHaveAccount: "ਕੀ ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ? ਸਾਈਨ ਇਨ ਕਰੋ",
        or: "ਜਾਂ"
    },
    or: {
        welcome: "ନମସ୍କାର!",
        tagline: "ଆପଣଙ୍କର ଉପଯୁକ୍ତ ଜୀବନସାଥୀ ଖୋଜନ୍ତୁ",
        heroTitle: "ଆପଣଙ୍କର ଉପଯୁକ୍ତ ବିବାହ ବାୟୋଡାଟା ତିଆରି କରନ୍ତୁ",
        heroSubtitle: "ପ୍ରଫେସନାଲ୍ ଟେମ୍ପଲେଟ୍ • ରିୟଲ୍-ଟାଇମ୍ ପ୍ରିଭ୍ୟୁ • ଇନଷ୍ଟାଣ୍ଟ PDF",
        startFree: "ମାଗଣାରେ ଆରମ୍ଭ କରନ୍ତୁ →",
        learnMore: "ଅଧିକ ଜାଣନ୍ତୁ ↓",
        features: "ବୈଶିଷ୍ଟ୍ୟଗୁଡିକ",
        pricing: "ମୂଲ୍ୟ",
        signIn: "ଲଗ୍ ଇନ୍ କରନ୍ତୁ",
        getStarted: "ଆରମ୍ଭ କରନ୍ତୁ",
        dashboard: "ଡ୍ୟାସବୋର୍ଡ",
        whyChoose: "ShadiBio କାହିଁକି ବାଛିବେ?",
        stunningBiodatas: "ସୁନ୍ଦର ବାୟୋଡାଟା ତିଆରି କରିବା ପାଇଁ ଆପଣଙ୍କୁ ଯାହା ଦରକାର ସବୁକିଛି",
        beautifulTemplates: "ସୁନ୍ଦର ଟେମ୍ପଲେଟ୍",
        traditionalModern: "ପାରମ୍ପାରିକ ଏବଂ ଆଧୁନିକ ଡିଜାଇନ୍",
        realTimePreview: "ରିୟଲ୍-ଟାଇମ୍ ପ୍ରିଭ୍ୟୁ",
        liveUpdates: "ଆପଣ ଟାଇପ୍ କରିବା ସମୟରେ ଲାଇଭ୍ ଅପଡେଟ୍",
        pdfDownload: "PDF ଡାଉନଲୋଡ୍",
        highQualityPdfs: "ଉଚ୍ଚ ଗୁଣବତ୍ତା ଇନଷ୍ଟାଣ୍ଟ PDF",
        privacyControls: "ଗୋପନୀୟତା ନିୟନ୍ତ୍ରଣ",
        yourDataControl: "ଆପଣଙ୍କ ଡାଟା, ଆପଣଙ୍କ ନିୟନ୍ତ୍ରଣ",
        multiLanguage: "ବହୁଭାଷୀ",
        languagesSupported: "୧୨+ ଭାଷା ସମର୍ଥିତ",
        smartFeatures: "ସ୍ମାର୍ଟ ବୈଶିଷ୍ଟ୍ୟଗୁଡିକ",
        autoCalcHistory: "ଅଟୋ-କାଲକୁଲେସନ୍ ଏବଂ ଭର୍ସନ୍ ଇତିହାସ",
        happyUsers: "ଖୁସି ଉପଯୋଗକର୍ତ୍ତା",
        biodatasCreated: "ବାୟୋଡାଟା ସୃଷ୍ଟି ହୋଇଛି",
        uptime: "ଅପଟାଇମ୍",
        userRating: "ଉପଯୋଗକର୍ତ୍ତା ରେଟିଂ",
        pricingTitle: "ସରଳ ଏବଂ ସ୍ୱଚ୍ଛ ମୂଲ୍ୟ",
        pricingSubtitle: "ଆପଣଙ୍କ ପାଇଁ ଉପଯୁକ୍ତ ପ୍ଲାନ୍ ବାଛନ୍ତୁ",
        mostPopular: "ସବୁଠାରୁ ଲୋକପ୍ରିୟ",
        free: "ମାଗଣା",
        premium: "ପ୍ରିମିୟମ୍",
        lifetime: "ଆଜୀବନ",
        forever: "ସବୁଦିନ ପାଇଁ",
        month: "/ମାସ",
        oneTime: "ଥରେ",
        goPremium: "ପ୍ରିମିୟମ୍ ନିଅନ୍ତୁ",
        getLifetime: "ଆଜୀବନ ନିଅନ୍ତୁ",
        footerText: "© ୨୦୨୪ ShadiBio. ଆପଣଙ୍କ ଉପଯୁକ୍ତ ସାଥୀ ଖୋଜିବା ପାଇଁ ❤️ ସହିତ ତିଆରି",
        privacy: "ଗୋପନୀୟତା",
        terms: "ସର୍ତ୍ତାବଳୀ",
        contact: "ଯୋଗାଯୋଗ",
        signInAccount: "ଆପଣଙ୍କର ଆକାଉଣ୍ଟକୁ ଲଗ୍ ଇନ୍ କରନ୍ତୁ",
        emailAddress: "ଇମେଲ୍ ଠିକଣା",
        password: "ପାସୱାର୍ଡ",
        rememberMe: "ମୋତେ ମନେରଖନ୍ତୁ",
        signingIn: "ଲଗ୍ ଇନ୍ ହେଉଛି...",
        notHaveAccount: "ଆକାଉଣ୍ଟ ନାହିଁ କି? ସାଇନ୍ ଅପ୍ କରନ୍ତୁ",
        createAccount: "ନୂତନ ଆକାଉଣ୍ଟ ସୃଷ୍ଟି କରନ୍ତୁ",
        fullName: "ପୂରା ନାମ",
        confirmPassword: "ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ",
        creatingAccount: "ଆକାଉଣ୍ଟ ସୃଷ୍ଟି ହେଉଛି...",
        alreadyHaveAccount: "ପୂର୍ବରୁ ଆକାଉଣ୍ଟ ଅଛି କି? ଲଗ୍ ଇନ୍ କରନ୍ତୁ",
        or: "କିମ୍ବା"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => {
        const langTranslations = translations[language];
        if (langTranslations && langTranslations[key]) {
            return langTranslations[key];
        }
        return translations['en'][key] || key;
    };

    return React.createElement(
        LanguageContext.Provider,
        { value: { language, setLanguage, t } },
        children
    );
};

export const useLanguage = () => useContext(LanguageContext);
